# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl_dart
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_dart/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl_e2e_tests
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl_e2e_tests_flutter
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl_e2e_tests_standalone_dart
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_flutter
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_flutter/example
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl_flutter_ce
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_flutter_ee
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_flutter_local
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_flutter_platform_interface
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_flutter_prebuilt
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl_flutter_prebuilt_e2e_tests
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /packages/cbl_generator
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_libcblite_api
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_libcblitedart_api
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_sentry
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pub
    directory: /packages/cbl_sentry/example
    schedule:
      interval: weekly
