runners:
  ubuntu22-2cpu:
    cpu: 2
    family: [m7, c7, m8, c8]
    image: ubuntu22-full-x64
    extras: s3-cache

  ubuntu22-4cpu:
    cpu: 4
    family: [m7, c7, m8, c8]
    image: ubuntu22-full-x64
    extras: s3-cache

  ubuntu22-2cpu-benchmark:
    cpu: 2
    family: m7a
    image: ubuntu22-full-x64
    extras: s3-cache

  windows22-2cpu:
    cpu: 2
    family: [m7, c7, m8, c8]
    image: windows22-full-x64
    extras: s3-cache
