include: all_lint_rules.yaml

analyzer:
  exclude:
    - node_modules/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: false

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
    prefer_asserts_with_message: false
    public_member_api_docs: false
    require_trailing_commas: false
