include: all_lint_rules.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
  exclude:
    - node_modules/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: false

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_use_package_imports: false
    prefer_asserts_with_message: false
    public_member_api_docs: false
    require_trailing_commas: false
    avoid_redundant_argument_values: false
