ignore:
  # Ignore all test code
  - 'packages/**/test'
  - 'packages/**/integration_test'
  - 'packages/cbl_e2e_tests'

codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        threshold: .2%
