name: cbl_dart
repository: https://github.com/cbl-dart/cbl-dart
packages:
  - packages/*
  - packages/*/example

ide:
  intellij: false

command:
  bootstrap:
    runPubGetInParallel: false

  version:
    hooks:
      preCommit:
        description:
          Pre-commit hook for the version command to update the
          `cbl_flutter_ce|ee` packages.
        run: |
          melos build:cbl_flutter_prebuilt && \
          git add packages/cbl_flutter_ee packages/cbl_flutter_ce && \
          melos build:cbl_dart:version_info && \
          git add packages/cbl_dart/lib/src/version_info.dart

scripts:
  build:cbl_flutter_prebuilt:
    description: Builds the prebuild packages `cbl_flutter_ce|ee`.
    run: cd packages/cbl_flutter_prebuilt && dart run

  build:cbl_dart:version_info:
    description: Builds the version_info.dart file in `cbl_dart` .
    run: cd packages/cbl_dart && dart run tool/generate_version_info.dart

  build:nativeLibraries:
    description: Builds the native libraries for the host target.
    run: ./tools/dev-tools.sh prepareNativeLibraries

  formatting:apply:
    description: Formats all Dart files.
    run: daco format .

  formatting:check:
    description: Formats all Dart files. Fails when files were changed.
    run: daco format --set-exit-if-changed .

  analyze:
    description: Analyzes all Dart files.
    run: dart analyze --fatal-infos

  test:setupCouchbaseClusterDocker:
    description: Sets up Couchbase services for testing in docker.
    exec: ./couchbase-services.sh setupDocker
    packageFilters:
      scope: cbl_e2e_tests

  test:teardownCouchbaseClusterDocker:
    description: Tears down Couchbase services for testing in docker.
    exec: ./couchbase-services.sh teardownDocker
    packageFilters:
      scope: cbl_e2e_tests

  test:startSyncGatewayMacOS:
    description: Starts Sync Gateway for testing on macOS.
    exec: ./couchbase-services.sh startSyncGatewayMacOS
    packageFilters:
      scope: cbl_e2e_tests

  test:waitForSyncGateway:
    description: Waits Sync Gateway for testing to become available.
    exec: ./couchbase-services.sh waitForSyncGateway
    packageFilters:
      scope: cbl_e2e_tests
