name: cbl_dart

packages:
  - packages/**

scripts:
  flutter:prepare:
    description: Runs `flutter pub get` followed by `melos bootstrap` in all flutter packages.
    run: melos run flutter:pub_get --no-select && melos run flutter:bootstrap

  flutter:pub_get:
    run: melos exec -- flutter pub get
    description:
      Runs `flutter pub get` in all flutter packages, to generate files
      which `melos bootstrap` doesn't.
    select-package:
      flutter: true

  flutter:bootstrap:
    run: melos bootstrap --flutter

  install:binaries:all:
    description: Installs the latest published binaries into `cbl_flutter`.
    run: melos exec --scope cbl_flutter -- ./tool/install_binaries.sh all

  formatting:check: melos exec -- dart format --set-exit-if-changed .

  analyze: melos exec -- dart analyze --fatal-infos

  build:cbl_flutter:test:ios:
    description: Builds the e2e tests for `cbl_flutter`.
    run: melos exec -- flutter build ios --no-pub --simulator integration_test/cbl_e2e_test.dart
    select-package:
      scope: cbl_flutter_example

  test:setupCouchbaseClusterDocker:
    run: melos exec -- "./couchbase-cluster.sh setupDocker"
    select-package:
      scope: cbl_e2e_tests

  test:teardownCouchbaseClusterDocker:
    run: melos exec -- "./couchbase-cluster.sh teardownDocker"
    select-package:
      scope: cbl_e2e_tests

  test:setupCouchbaseClusterMacOS:
    run: melos exec -- "./couchbase-cluster.sh setupMacOS"
    select-package:
      scope: cbl_e2e_tests

  test:all: melos run test:cbl &&
    melos run test:cbl_ffi &&
    melos run test:cbl_native &&
    melos run test:standalone_dart &&
    melos run test:flutter:macos &&
    melos run test:flutter:ios &&
    melos run test:flutter:android

  test:cbl:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      scope: 'cbl'

  test:cbl_ffi:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      scope: 'cbl_ffi'

  test:cbl_native:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      scope: 'cbl_native'

  test:standalone_dart:
    run: melos exec -- dart test -r expanded -j 1
    select-package:
      scope: 'cbl_e2e_tests_standalone_dart'

  test:flutter:macos:
    run: melos exec --
      flutter test
      --no-pub
      -r expanded
      -d macOS
      integration_test/cbl_e2e_test.dart
    select-package:
      scope: 'cbl_flutter_example'

  test:flutter:ios:
    run: melos exec --
      flutter test
      --no-pub
      -r expanded
      -d iPhone
      integration_test/cbl_e2e_test.dart
    select-package:
      scope: 'cbl_flutter_example'

  test:flutter:android:
    run: melos exec --
      flutter test
      --no-pub
      -r expanded
      -d emulator
      integration_test/cbl_e2e_test.dart
    select-package:
      scope: 'cbl_flutter_example'

  version:cbl_native:update_lib:
    description: Updates the hard coded `currentVersion` in `cbl_native`.
      Must be run before publishing and after bumping the version of
      `cbl_native` in pubspec.yaml.
    run: melos exec -- dart run tool/update_version.dart
    select-package:
      scope: 'cbl_native'

  clean:packages:
    run: git clean -xdfq packages

  clean:all:
    run: git clean -xdfq .
