name: cbl_dart
repository: https://github.com/cbl-dart/cbl-dart
packages:
  - packages/*
  - packages/*/example

ide:
  intellij: false

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  formatting:apply:
    description: Formats all Dart files.
    run: daco format .

  formatting:check:
    description: Formats all Dart files. Fails when files were changed.
    run: daco format --set-exit-if-changed .

  analyze:
    description: Analyzes all Dart files.
    run: dart analyze --fatal-infos

  test:setupCouchbaseClusterDocker:
    description: Sets up Couchbase services for testing in docker.
    exec: ./couchbase-services.sh setupDocker
    packageFilters:
      scope: cbl_e2e_tests

  test:teardownCouchbaseClusterDocker:
    description: Tears down Couchbase services for testing in docker.
    exec: ./couchbase-services.sh teardownDocker
    packageFilters:
      scope: cbl_e2e_tests

  test:startSyncGatewayMacOS:
    description: Starts Sync Gateway for testing on macOS.
    exec: ./couchbase-services.sh startSyncGatewayMacOS
    packageFilters:
      scope: cbl_e2e_tests

  test:waitForSyncGateway:
    description: Waits Sync Gateway for testing to become available.
    exec: ./couchbase-services.sh waitForSyncGateway
    packageFilters:
      scope: cbl_e2e_tests
