name: cbl_dart
repository: https://github.com/cbl-dart/cbl-dart
packages:
  - packages/**
ignore:
  - packages/cbl_e2e_tests*/*
  - packages/cbl_flutter_?e/*
  - packages/cbl_flutter_local/*
  - packages/cbl_flutter_prebuilt*/*
command:
  version:
    linkToCommits: true

scripts:
  build:cbl_flutter_prebuilt:
    description: Builds the prebuild packages `cbl_flutter_ce|ee`.
    run: cd packages/cbl_flutter_prebuilt && dart run

  build:nativeLibraries:
    description: Builds the native libraries for the host target.
    run: ./tools/dev-tools.sh prepareNativeLibraries

  flutter:pubGet:
    description: Runs pub get in all Flutter packages.
    run: melos exec --flutter -- flutter pub get

  formatting:apply:
    description: Formats all Dart files.
    run: dart format .

  formatting:check:
    description: Formats all Dart files. Fails when files were changed.
    run: dart format --set-exit-if-changed .

  analyze:
    description: Analyzes all Dart files.
    run: melos exec -- dart analyze --fatal-infos

  test:setupCouchbaseClusterDocker:
    description: Sets up Couchbase services for testing in docker.
    run: melos exec -- "./couchbase-services.sh setupDocker"
    select-package:
      scope: cbl_e2e_tests

  test:teardownCouchbaseClusterDocker:
    description: Tears down Couchbase services for testing in docker.
    run: melos exec -- "./couchbase-services.sh teardownDocker"
    select-package:
      scope: cbl_e2e_tests

  test:startSyncGatewayMacOS:
    description: Starts Sync Gateway for testing on macOS.
    run: melos exec -- "./couchbase-services.sh startSyncGatewayMacOS"
    select-package:
      scope: cbl_e2e_tests

  test:waitForSyncGateway:
    description: Waits Sync Gateway for testing to become available.
    run: melos exec -- "./couchbase-services.sh waitForSyncGateway"
    select-package:
      scope: cbl_e2e_tests
