name: cbl_dart
repository: https://github.com/cbl-dart/cbl-dart
packages:
  - packages/**
command:
  version:
    linkToCommits: true

scripts:
  build:cbl_flutter_prebuilt:
    run: melos exec -- dart run
    select-package:
      scope: cbl_flutter_prebuilt

  build:nativeLibraries:
    run: ./tools/dev-tools.sh prepareNativeLibraries

  flutter:pubGet:
    run: melos exec --flutter -- flutter pub get

  formatting:check: melos exec -- dart format --set-exit-if-changed .

  analyze: melos exec -- dart analyze --fatal-infos

  test:setupCouchbaseClusterDocker:
    run: melos exec -- "./couchbase-cluster.sh setupDocker"
    select-package:
      scope: cbl_e2e_tests

  test:teardownCouchbaseClusterDocker:
    run: melos exec -- "./couchbase-cluster.sh teardownDocker"
    select-package:
      scope: cbl_e2e_tests

  test:setupCouchbaseClusterMacOS:
    run: melos exec -- "./couchbase-cluster.sh setupMacOS"
    select-package:
      scope: cbl_e2e_tests

  clean:packages:
    run: git clean -xdfq packages

  clean:all:
    run: git clean -xdfq .
