name: cbl_dart

packages:
  - packages/**

scripts:
  build:cbl_flutter_prebuilt:
    run: melos exec -- dart run
    select-package:
      scope: cbl_flutter_prebuilt

  formatting:check: melos exec -- dart format --set-exit-if-changed .

  analyze: melos exec -- dart analyze --fatal-infos

  test:setupCouchbaseClusterDocker:
    run: melos exec -- "./couchbase-cluster.sh setupDocker"
    select-package:
      scope: cbl_e2e_tests

  test:teardownCouchbaseClusterDocker:
    run: melos exec -- "./couchbase-cluster.sh teardownDocker"
    select-package:
      scope: cbl_e2e_tests

  test:setupCouchbaseClusterMacOS:
    run: melos exec -- "./couchbase-cluster.sh setupMacOS"
    select-package:
      scope: cbl_e2e_tests

  test:cbl:
    run: melos exec -- flutter test --no-pub -r expanded
    select-package:
      scope: 'cbl'

  clean:packages:
    run: git clean -xdfq packages

  clean:all:
    run: git clean -xdfq .
