name: cbl_dart_repo
publish_to: none

environment:
  sdk: ^3.10.0

hooks:
  user_defines:
    cbl:
      edition: enterprise
      vector_search: true

workspace:
  - packages/benchmark
  - packages/cbl
  - packages/cbl/example
  - packages/cbl_e2e_tests
  - packages/cbl_e2e_tests_flutter
  - packages/cbl_e2e_tests_standalone_dart
  - packages/cbl_generator
  - packages/cbl_sentry
  - packages/cbl_sentry/example
  - tool

dev_dependencies:
  cbd:
    path: tool
  daco: ^0.5.1
  melos: ^7.4.0
  path: ^1.9.1

dependency_overrides:
  meta: ^1.18.0
  test: 1.31.0
  test_api: 0.7.11
  test_core: 0.6.17

melos:
  repository: https://github.com/cbl-dart/cbl-dart
  ignore:
    - packages/cbl_*_api

  ide:
    intellij: false

  command:
    bootstrap:
      runPubGetInParallel: false

  scripts:
    activate:cbd:
      description: Activates CBL Dart project dev tools CLI.
      run: cd tool && dart pub global activate --source path .

    formatting:apply:
      description: Formats all Dart files.
      run: daco format .

    formatting:check:
      description: Formats all Dart files. Fails when files were changed.
      run: daco format --set-exit-if-changed .

    analyze:
      description: Analyzes all Dart files.
      run: dart analyze --fatal-infos

    test:unit:
      description: Runs unit tests (non-e2e).
      exec: dart test
      packageFilters:
        scope:
          - cbl
          - cbl_generator
          - cbl_sentry

    quality-gates:
      description: Runs formatting check, analyzer, and unit tests.
      steps:
        - formatting:check
        - analyze
        - test:unit

    test:setupCouchbaseClusterDocker:
      description: Sets up Couchbase services for testing in docker.
      exec: ./couchbase-services.sh setupDocker
      packageFilters:
        scope: cbl_e2e_tests

    test:teardownCouchbaseClusterDocker:
      description: Tears down Couchbase services for testing in docker.
      exec: ./couchbase-services.sh teardownDocker
      packageFilters:
        scope: cbl_e2e_tests

    test:startSyncGatewayMacOS:
      description: Starts Sync Gateway for testing on macOS.
      exec: ./couchbase-services.sh startSyncGatewayMacOS
      packageFilters:
        scope: cbl_e2e_tests

    test:waitForSyncGateway:
      description: Waits Sync Gateway for testing to become available.
      exec: ./couchbase-services.sh waitForSyncGateway
      packageFilters:
        scope: cbl_e2e_tests
