name: cbl_sentry_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  cbl: ^4.0.0-dev.1
  cbl_sentry:
    path: ..
  sentry: ^9.14.0
