#!/usr/bin/env bash

set -e

function requireEnvVar() {
    local envVar="$1"

    if [[ -z "${!envVar}" ]]; then
        echo "$envVar is a required environment variable, but is not set"
        exit 1
    fi
}

requireEnvVar MATRIX_EMBEDDER
requireEnvVar MATRIX_OS

# === Constants ===============================================================

testResultsDir="test-results"
standaloneTestsPackage="cbl_e2e_tests_standalone_dart"
flutterTestsPackage="cbl_e2e_tests_flutter"
standaloneTestsPackageDir="packages/$standaloneTestsPackage"
flutterTestsPackageDir="packages/$flutterTestsPackage"
testAppBundleId="com.terwesten.gabriel.cblE2eTestsFlutter"
iosVersion="14-5"
iosDevice="iPhone 12"
androidVersion="22"
androidDevice="pixel_4"

# === Steps ===================================================================

function buildNativeLibraries() {
    local target=

    case "$MATRIX_OS" in
    iOS)
        target=ios
        ;;
    macOS)
        target=macos
        ;;
    Android)
        target=android
        ;;
    Ubuntu)
        target=ubuntu20.04-x86_64
        ;;
    esac

    ./tool/dev-tools.sh prepareNativeLibraries enterprise debug "$target"
}

function configureFlutter() {
    case "$MATRIX_OS" in
    macOS)
        flutter config --enable-macos-desktop
        ;;
    Ubuntu)
        flutter config --enable-linux-desktop
        ;;
    esac
}

function bootstrapPackages() {
    case "$MATRIX_EMBEDDER" in
    standalone)
        melos bootstrap --scope "$standaloneTestsPackage"
        ;;
    flutter)
        # `flutter pub get` creates some files which `melos bootstrap` doesn't.
        melos exec --scope "$flutterTestsPackage" -- flutter pub get
        melos bootstrap --scope "$flutterTestsPackage"
        ;;
    esac
}

function startVirtualDevices() {
    case "$MATRIX_OS" in
    iOS)
        ./tool/apple-simulator.sh start -o "iOS-$iosVersion" -d "$iosDevice"
        ;;
    Android)
        ./tool/android-emulator.sh createAndStart -a "$androidVersion" -d "$androidDevice"
        ./tool/android-emulator.sh setupReversePort 4984
        ./tool/android-emulator.sh setupReversePort 4985
        ;;
    Ubuntu)
        Xvfb :99 &
        echo "DISPLAY=:99" >>$GITHUB_ENV
        ;;
    esac
}

function runE2ETests() {
    case "$MATRIX_EMBEDDER" in
    standalone)
        cd "$standaloneTestsPackageDir"

        export ENABLE_TIME_BOMB=true
        testCommand="dart test -r expanded -j 1"

        case "$MATRIX_OS" in
        macOS)
            # The tests are run with sudo, so that macOS records crash reports.
            sudo $testCommand
            ;;
        Ubuntu)
            # Enable core dumps.
            ulimit -c unlimited
            $testCommand
            ;;
        esac
        ;;
    flutter)
        cd "$flutterTestsPackageDir"

        device=""
        case "$MATRIX_OS" in
        iOS)
            device="iPhone"
            ;;
        macOS)
            device="macOS"
            ;;
        Android)
            device="Android"
            ;;
        Ubuntu)
            # Enable core dumps.
            device="Linux"
            ulimit -c unlimited
            echo "core.%p" >/proc/sys/kernel/core_pattern
            ;;
        esac

        flutter drive \
            --no-pub \
            -d "$device" \
            --dart-define enableTimeBomb=true \
            --keep-app-running \
            --driver test_driver/integration_test.dart \
            --target integration_test/cbl_e2e_test.dart
        ;;
    esac
}

function _collectFlutterIntegrationResponseData() {
    echo "Collecting Flutter integration test response data"

    local integrationResponseData="$flutterTestsPackageDir/build/integration_response_data"

    if [ ! -e "$integrationResponseData" ]; then
        echo "Did not find data"
        return 0
    fi

    echo "Copying data..."
    cp -a "$integrationResponseData" "$testResultsDir"
    echo "Copied data"
}

function _collectCrashReportsMacOS() {
    # Crash reports are generated by the OS.
    echo "Copying macOS DiagnosticReports..."
    cp -a ~/Library/Logs/DiagnosticReports "$testResultsDir"
    echo "Copied macOS DiagnosticReports"
}

function _collectCrashReportsLinuxStandalone() {
    ./tool/create-crash-report-linux.sh \
        -e "$(which dart)" \
        -c "$standaloneTestsPackageDir/core" \
        -o "$testResultsDir"
}

function _collectCrashReportsLinuxFlutter() {
    for core in "$flutterTestsPackageDir/core."*; do
        local pid="${core##*.}"
        local coreTestResultsDir="$testResultsDir/$pid"
        mkdir -p "$coreTestResultsDir"

        ./tool/create-crash-report-linux.sh \
            -e "$flutterTestsPackageDir/build/linux/x64/debug/bundle/$flutterTestsPackage" \
            -c "$flutterTestsPackageDir/core" \
            -o "$coreTestResultsDir"
    done
}

function _collectCrashReportsAndroid() {
    ./tool/android-emulator.sh bugreport -o "$testResultsDir"
}

function _collectCblLogsStandalone() {
    echo "Collecting Couchbase Lite logs"

    local cblLogsDir="$standaloneTestsPackageDir/test/.tmp/logs"

    if [ ! -e "$cblLogsDir" ]; then
        echo "Did not find logs"
        return 0
    fi

    echo "Copying files..."
    cp -a "$cblLogsDir" "$testResultsDir"
    echo "Copied files"
}

function _collectCblLogsIosSimulator() {
    echo "Collecting Couchbase Lite logs from iOS Simulator app"

    ./tool/apple-simulator.sh copyData \
        -o "iOS-$iosVersion" \
        -d "$iosDevice" \
        -b "$testAppBundleId" \
        -f "Library/Caches/cbl_flutter/logs" \
        -t "$testResultsDir"
}

function _collectCblLogsMacOS() {
    echo "Collecting Couchbase Lite logs from macOS app"

    local appDataContainer="~/Library/Containers/$testAppBundleId/Data"
    local cblLogsDir="$appDataContainer/Library/Caches/cbl_flutter/logs"

    if [ ! -e "$cblLogsDir" ]; then
        echo "Did not find logs"
        return 0
    fi

    echo "Copying files..."
    cp -a "$cblLogsDir" "$testResultsDir"
    echo "Copied files"
}

function collectTestResults() {
    mkdir "$testResultsDir"

    # Wait for crash reports/core dumps.
    sleep 60

    case "$MATRIX_EMBEDDER" in
    standalone)
        case "$MATRIX_OS" in
        macOS)
            _collectCrashReportsMacOS
            _collectCblLogsStandalone
            ;;
        Ubuntu)
            _collectCrashReportsLinuxStandalone
            _collectCblLogsStandalone
            ;;
        esac
        ;;
    flutter)
        _collectFlutterIntegrationResponseData

        case "$MATRIX_OS" in
        macOS)
            _collectCrashReportsMacOS
            _collectCblLogsMacOS
            ;;
        iOS)
            _collectCrashReportsMacOS
            _collectCblLogsIosSimulator
            ;;
        Android)
            _collectCrashReportsAndroid
            # TODO get cbl logs from device
            ;;
        Ubuntu)
            _collectCrashReportsLinuxFlutter
            # TODO get cbl logs from device
            ;;
        esac
        ;;
    esac
}

"$@"
