name: cbd
description: CBL Dart project dev tools CLI
publish_to: 'none'

executables:
  cbd:

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.8.0
  args: ^2.6.0
  cbl: ^3.3.0
  cli_launcher: ^0.3.1
  cli_util: ^0.4.2
  collection: ^1.19.1
  dart_style: ^2.3.1
  meta: ^1.16.0
  package_config: ^2.1.0
  path: ^1.9.1
  pub_semver: ^2.1.4
  yaml: ^3.1.2
