name: cbd
description: CBL Dart project dev tools CLI
publish_to: 'none'

executables:
  cbd:

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  cbl: ^3.2.1
  cli_launcher: ^0.3.1
  meta: ^1.16.0
  path: ^1.9.1
