version: '3.1'
services:
  devcontainer:
    build: ../../.devcontainer
    command: sleep infinity
    volumes:
      - ../..:/workspace:cached
    user: vscode
    network_mode: service:sync-gateway
