// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:cbl/src/bindings/cblitedart.dart')
library;

import 'dart:ffi' as ffi;
import 'package:cbl/src/bindings/cblite.dart' as imp$1;
import '' as self;

@ffi.Native<NativeCBLDart_FLSliceResult_RetainByBuf>(isLeaf: true)
external void CBLDart_FLSliceResult_RetainByBuf(ffi.Pointer<ffi.Void> buf);

@ffi.Native<NativeCBLDart_FLSliceResult_ReleaseByBuf>(isLeaf: true)
external void CBLDart_FLSliceResult_ReleaseByBuf(ffi.Pointer<ffi.Void> buf);

@ffi.Native<NativeCBLDart_FLSlice_Equal>(isLeaf: true)
external bool CBLDart_FLSlice_Equal(
  ffi.Pointer<ffi.Void> aBuf,
  int aSize,
  ffi.Pointer<ffi.Void> bBuf,
  int bSize,
);

@ffi.Native<NativeCBLDart_FLSlice_Compare>(isLeaf: true)
external int CBLDart_FLSlice_Compare(
  ffi.Pointer<ffi.Void> aBuf,
  int aSize,
  ffi.Pointer<ffi.Void> bBuf,
  int bSize,
);

@ffi.Native<NativeCBLDart_FLSlice_Copy>(isLeaf: true)
external FLSliceResult CBLDart_FLSlice_Copy(
  ffi.Pointer<ffi.Void> buf,
  int size,
);

@ffi.Native<NativeCBLDart_FLData_Dump>(isLeaf: true)
external imp$1.FLStringResult CBLDart_FLData_Dump(
  ffi.Pointer<ffi.Void> dataBuf,
  int dataSize,
);

@ffi.Native<NativeCBLDart_FLValue_FromData>(isLeaf: true)
external imp$1.FLValue CBLDart_FLValue_FromData(
  ffi.Pointer<ffi.Void> buf,
  int size,
  int trust,
);

@ffi.Native<NativeCBLDart_FLDoc_FromResultData>(isLeaf: true)
external imp$1.FLDoc CBLDart_FLDoc_FromResultData(
  ffi.Pointer<ffi.Void> dataBuf,
  int dataSize,
  int trust,
  imp$1.FLSharedKeys sharedKeys,
  ffi.Pointer<ffi.Void> externBuf,
  int externSize,
);

@ffi.Native<NativeCBLDart_FLDoc_FromJSON>(isLeaf: true)
external imp$1.FLDoc CBLDart_FLDoc_FromJSON(
  ffi.Pointer<ffi.Void> jsonBuf,
  int jsonSize,
  ffi.Pointer<ffi.UnsignedInt> outError,
);

@ffi.Native<NativeCBLDart_FLDict_Get>(isLeaf: true)
external imp$1.FLValue CBLDart_FLDict_Get(
  imp$1.FLDict dict,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_FLDictKey_Init>(isLeaf: true)
external FLDictKey CBLDart_FLDictKey_Init(
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_FLMutableDict_Set>(isLeaf: true)
external imp$1.FLSlot CBLDart_FLMutableDict_Set(
  imp$1.FLMutableDict dict,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_FLMutableDict_Remove>(isLeaf: true)
external void CBLDart_FLMutableDict_Remove(
  imp$1.FLMutableDict dict,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_FLMutableDict_GetMutableArray>(isLeaf: true)
external imp$1.FLMutableArray CBLDart_FLMutableDict_GetMutableArray(
  imp$1.FLMutableDict dict,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_FLMutableDict_GetMutableDict>(isLeaf: true)
external imp$1.FLMutableDict CBLDart_FLMutableDict_GetMutableDict(
  imp$1.FLMutableDict dict,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_FLSlot_SetString>(isLeaf: true)
external void CBLDart_FLSlot_SetString(
  imp$1.FLSlot slot,
  ffi.Pointer<ffi.Void> valueBuf,
  int valueSize,
);

@ffi.Native<NativeCBLDart_FLSlot_SetData>(isLeaf: true)
external void CBLDart_FLSlot_SetData(
  imp$1.FLSlot slot,
  ffi.Pointer<ffi.Void> dataBuf,
  int dataSize,
);

@ffi.Native<NativeCBLDart_KnownSharedKeys_New>(isLeaf: true)
external ffi.Pointer<KnownSharedKeys> CBLDart_KnownSharedKeys_New();

@ffi.Native<NativeCBLDart_KnownSharedKeys_Delete>(isLeaf: true)
external void CBLDart_KnownSharedKeys_Delete(ffi.Pointer<KnownSharedKeys> keys);

@ffi.Native<NativeCBLDart_GetLoadedFLValue>(isLeaf: true)
external void CBLDart_GetLoadedFLValue(
  imp$1.FLValue value,
  ffi.Pointer<CBLDart_LoadedFLValue> out,
);

@ffi.Native<NativeCBLDart_FLArray_GetLoadedFLValue>(isLeaf: true)
external void CBLDart_FLArray_GetLoadedFLValue(
  imp$1.FLArray array,
  int index,
  ffi.Pointer<CBLDart_LoadedFLValue> out,
);

@ffi.Native<NativeCBLDart_FLDict_GetLoadedFLValue>(isLeaf: true)
external void CBLDart_FLDict_GetLoadedFLValue(
  imp$1.FLDict dict,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
  ffi.Pointer<CBLDart_LoadedFLValue> out,
);

@ffi.Native<NativeCBLDart_FLDictIterator_Begin>(isLeaf: true)
external ffi.Pointer<CBLDart_FLDictIterator> CBLDart_FLDictIterator_Begin(
  imp$1.FLDict dict,
  ffi.Pointer<KnownSharedKeys> knownSharedKeys,
  ffi.Pointer<CBLDart_LoadedDictKey> keyOut,
  ffi.Pointer<CBLDart_LoadedFLValue> valueOut,
  bool deleteOnDone,
  bool preLoad,
);

@ffi.Native<NativeCBLDart_FLDictIterator_Delete>(isLeaf: true)
external void CBLDart_FLDictIterator_Delete(
  ffi.Pointer<CBLDart_FLDictIterator> iterator,
);

@ffi.Native<NativeCBLDart_FLDictIterator_Next>(isLeaf: true)
external bool CBLDart_FLDictIterator_Next(
  ffi.Pointer<CBLDart_FLDictIterator> iterator,
);

@ffi.Native<NativeCBLDart_FLArrayIterator_Begin>(isLeaf: true)
external ffi.Pointer<CBLDart_FLArrayIterator> CBLDart_FLArrayIterator_Begin(
  imp$1.FLArray array,
  ffi.Pointer<CBLDart_LoadedFLValue> valueOut,
  bool deleteOnDone,
);

@ffi.Native<NativeCBLDart_FLArrayIterator_Delete>(isLeaf: true)
external void CBLDart_FLArrayIterator_Delete(
  ffi.Pointer<CBLDart_FLArrayIterator> iterator,
);

@ffi.Native<NativeCBLDart_FLArrayIterator_Next>(isLeaf: true)
external bool CBLDart_FLArrayIterator_Next(
  ffi.Pointer<CBLDart_FLArrayIterator> iterator,
);

@ffi.Native<NativeCBLDart_FLEncoder_WriteArrayValue>(isLeaf: true)
external bool CBLDart_FLEncoder_WriteArrayValue(
  imp$1.FLEncoder encoder,
  imp$1.FLArray array,
  int index,
);

@ffi.Native<NativeCBLDart_FLEncoder_WriteString>(isLeaf: true)
external bool CBLDart_FLEncoder_WriteString(
  imp$1.FLEncoder encoder,
  ffi.Pointer<ffi.Void> strBuf,
  int strSize,
);

@ffi.Native<NativeCBLDart_FLEncoder_WriteKey>(isLeaf: true)
external bool CBLDart_FLEncoder_WriteKey(
  imp$1.FLEncoder encoder,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_FLEncoder_WriteData>(isLeaf: true)
external bool CBLDart_FLEncoder_WriteData(
  imp$1.FLEncoder encoder,
  ffi.Pointer<ffi.Void> dataBuf,
  int dataSize,
);

@ffi.Native<NativeCBLDart_FLEncoder_ConvertJSON>(isLeaf: true)
external bool CBLDart_FLEncoder_ConvertJSON(
  imp$1.FLEncoder encoder,
  ffi.Pointer<ffi.Void> jsonBuf,
  int jsonSize,
);

@ffi.Native<NativeCBLDart_CpuSupportsAVX2>(isLeaf: true)
external bool CBLDart_CpuSupportsAVX2();

@ffi.Native<NativeCBLDart_IsEnterprise>(isLeaf: true)
external bool CBLDart_IsEnterprise();

@ffi.Native<NativeCBLDart_Initialize>()
external int CBLDart_Initialize(
  ffi.Pointer<ffi.Void> dartInitializeDlData,
  ffi.Pointer<ffi.Void> cblInitContext,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_AsyncCallback_New>()
external CBLDart_AsyncCallback CBLDart_AsyncCallback_New(
  int id,
  int sendPort,
  bool debug,
);

@ffi.Native<NativeCBLDart_AsyncCallback_Delete>()
external void CBLDart_AsyncCallback_Delete(CBLDart_AsyncCallback callback);

@ffi.Native<NativeCBLDart_AsyncCallback_Close>()
external void CBLDart_AsyncCallback_Close(CBLDart_AsyncCallback callback);

@ffi.Native<NativeCBLDart_AsyncCallback_CallForTest>()
external void CBLDart_AsyncCallback_CallForTest(
  CBLDart_AsyncCallback callback,
  int argument,
);

@ffi.Native<NativeCBLDart_Completer_Complete>(isLeaf: true)
external void CBLDart_Completer_Complete(
  CBLDart_Completer completer,
  int result,
);

@ffi.Native<NativeCBLDart_AllocateIsolateId>(isLeaf: true)
external int CBLDart_AllocateIsolateId();

@ffi.Native<NativeCBLDart_SetCurrentIsolateId>(isLeaf: true)
external void CBLDart_SetCurrentIsolateId(int isolateId);

@ffi.Native<NativeCBLDart_GetCurrentIsolateId>(isLeaf: true)
external int CBLDart_GetCurrentIsolateId();

@ffi.Native<NativeCBLDart_CBLLog_AddCallback>(isLeaf: true)
external void CBLDart_CBLLog_AddCallback(
  CBLDart_AsyncCallback callback,
  imp$1.DartCBLLogLevel level,
);

@ffi.Native<NativeCBLDart_CBLLog_SetCallbackLevel>(isLeaf: true)
external void CBLDart_CBLLog_SetCallbackLevel(
  CBLDart_AsyncCallback callback,
  imp$1.DartCBLLogLevel level,
);

@ffi.Native<NativeCBLDart_CBLLog_SetFileSink>(isLeaf: true)
external void CBLDart_CBLLog_SetFileSink(ffi.Pointer<CBLFileLogSink> sink);

@ffi.Native<NativeCBLDart_CBLLog_GetFileSink>(isLeaf: true)
external ffi.Pointer<CBLFileLogSink> CBLDart_CBLLog_GetFileSink();

@ffi.Native<NativeCBLDart_CBL_LogMessage>(isLeaf: true)
external void CBLDart_CBL_LogMessage(
  imp$1.DartCBLLogDomain domain,
  imp$1.DartCBLLogLevel level,
  ffi.Pointer<ffi.Void> msgBuf,
  int msgSize,
);

@ffi.Native<NativeCBLDart_CBL_EnableVectorSearch>(isLeaf: true)
external bool CBLDart_CBL_EnableVectorSearch(
  ffi.Pointer<ffi.Void> dirBuf,
  int dirSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLDatabaseConfiguration_Default>(isLeaf: true)
external CBLDart_CBLDatabaseConfiguration
CBLDart_CBLDatabaseConfiguration_Default();

@ffi.Native<NativeCBLDart_CBL_CopyDatabase>(isLeaf: true)
external bool CBLDart_CBL_CopyDatabase(
  ffi.Pointer<ffi.Void> fromPathBuf,
  int fromPathSize,
  ffi.Pointer<ffi.Void> toNameBuf,
  int toNameSize,
  ffi.Pointer<CBLDart_CBLDatabaseConfiguration> config,
  ffi.Pointer<CBLError> outError,
);

@ffi.Native<NativeCBLDart_CBLDatabase_Open>(isLeaf: true)
external ffi.Pointer<CBLDatabase> CBLDart_CBLDatabase_Open(
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  ffi.Pointer<CBLDart_CBLDatabaseConfiguration> config,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLDatabase_Release>(isLeaf: true)
external void CBLDart_CBLDatabase_Release(ffi.Pointer<CBLDatabase> database);

@ffi.Native<NativeCBLDart_CBLDatabase_Close>(isLeaf: true)
external bool CBLDart_CBLDatabase_Close(
  ffi.Pointer<CBLDatabase> database,
  bool andDelete,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBL_DeleteDatabase>(isLeaf: true)
external bool CBLDart_CBL_DeleteDatabase(
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  ffi.Pointer<ffi.Void> inDirBuf,
  int inDirSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBL_DatabaseExists>(isLeaf: true)
external bool CBLDart_CBL_DatabaseExists(
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  ffi.Pointer<ffi.Void> inDirBuf,
  int inDirSize,
);

@ffi.Native<NativeCBLDart_CBLEncryptionKey_FromPassword>(isLeaf: true)
external bool CBLDart_CBLEncryptionKey_FromPassword(
  ffi.Pointer<CBLEncryptionKey> key,
  ffi.Pointer<ffi.Void> pwBuf,
  int pwSize,
);

@ffi.Native<NativeCBLDart_CBLDatabase_Scope>(isLeaf: true)
external ffi.Pointer<CBLScope> CBLDart_CBLDatabase_Scope(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLScope_Collection>(isLeaf: true)
external ffi.Pointer<CBLCollection> CBLDart_CBLScope_Collection(
  ffi.Pointer<CBLScope> scope,
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLDatabase_CreateCollection>(isLeaf: true)
external ffi.Pointer<CBLCollection> CBLDart_CBLDatabase_CreateCollection(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<ffi.Void> colNameBuf,
  int colNameSize,
  ffi.Pointer<ffi.Void> scopeNameBuf,
  int scopeNameSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLDatabase_DeleteCollection>(isLeaf: true)
external bool CBLDart_CBLDatabase_DeleteCollection(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<ffi.Void> colNameBuf,
  int colNameSize,
  ffi.Pointer<ffi.Void> scopeNameBuf,
  int scopeNameSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLCollection_GetDocument>(isLeaf: true)
external ffi.Pointer<CBLDocument> CBLDart_CBLCollection_GetDocument(
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> docIDBuf,
  int docIDSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLCollection_PurgeDocumentByID>(isLeaf: true)
external bool CBLDart_CBLCollection_PurgeDocumentByID(
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> docIDBuf,
  int docIDSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLCollection_GetDocumentExpiration>(isLeaf: true)
external imp$1.DartCBLTimestamp CBLDart_CBLCollection_GetDocumentExpiration(
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> docIDBuf,
  int docIDSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLCollection_SetDocumentExpiration>(isLeaf: true)
external bool CBLDart_CBLCollection_SetDocumentExpiration(
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> docIDBuf,
  int docIDSize,
  imp$1.DartCBLTimestamp expiration,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLCollection_AddDocumentChangeListener>(isLeaf: true)
external void CBLDart_CBLCollection_AddDocumentChangeListener(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> docIDBuf,
  int docIDSize,
  CBLDart_AsyncCallback listener,
);

@ffi.Native<NativeCBLDart_CBLCollection_AddChangeListener>(isLeaf: true)
external void CBLDart_CBLCollection_AddChangeListener(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<CBLCollection> collection,
  CBLDart_AsyncCallback listener,
);

@ffi.Native<NativeCBLDart_CBLCollection_GetIndex>(isLeaf: true)
external ffi.Pointer<CBLQueryIndex> CBLDart_CBLCollection_GetIndex(
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLCollection_CreateIndex>(isLeaf: true)
external bool CBLDart_CBLCollection_CreateIndex(
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  CBLDart_CBLIndexSpec indexSpec,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLCollection_DeleteIndex>(isLeaf: true)
external bool CBLDart_CBLCollection_DeleteIndex(
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLDocument_CreateWithID>(isLeaf: true)
external ffi.Pointer<CBLDocument> CBLDart_CBLDocument_CreateWithID(
  ffi.Pointer<ffi.Void> docIDBuf,
  int docIDSize,
);

@ffi.Native<NativeCBLDart_CBLDocument_SetJSON>(isLeaf: true)
external bool CBLDart_CBLDocument_SetJSON(
  ffi.Pointer<CBLDocument> doc,
  ffi.Pointer<ffi.Void> jsonBuf,
  int jsonSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLDatabase_CreateQuery>(isLeaf: true)
external ffi.Pointer<CBLQuery> CBLDart_CBLDatabase_CreateQuery(
  ffi.Pointer<CBLDatabase> db,
  imp$1.DartCBLQueryLanguage language,
  ffi.Pointer<ffi.Void> queryBuf,
  int querySize,
  ffi.Pointer<ffi.Int> errorPos,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLQuery_AddChangeListener>(isLeaf: true)
external ffi.Pointer<CBLListenerToken> CBLDart_CBLQuery_AddChangeListener(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<CBLQuery> query,
  CBLDart_AsyncCallback listener,
);

@ffi.Native<NativeCBLDart_CBLResultSet_ValueForKey>(isLeaf: true)
external imp$1.FLValue CBLDart_CBLResultSet_ValueForKey(
  ffi.Pointer<CBLResultSet> resultSet,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_PredictiveModel_New>(isLeaf: true)
external CBLDart_PredictiveModel CBLDart_PredictiveModel_New(
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
  int isolateId,
  CBLDart_PredictiveModel_PredictionSync predictionSync,
  CBLDart_PredictiveModel_PredictionAsync predictionAsync,
  CBLDart_PredictiveModel_Unregistered unregistered,
);

@ffi.Native<NativeCBLDart_PredictiveModel_Delete>()
external void CBLDart_PredictiveModel_Delete(CBLDart_PredictiveModel model);

@ffi.Native<NativeCBLDart_CBL_UnregisterPredictiveModel>()
external void CBLDart_CBL_UnregisterPredictiveModel(
  ffi.Pointer<ffi.Void> nameBuf,
  int nameSize,
);

@ffi.Native<NativeCBLDart_CBLBlobReader_Read>(isLeaf: true)
external FLSliceResult CBLDart_CBLBlobReader_Read(
  ffi.Pointer<CBLBlobReadStream> stream,
  int bufferSize,
  ffi.Pointer<CBLError> outError,
);

@ffi.Native<NativeCBLDart_CBLBlob_CreateWithData>(isLeaf: true)
external ffi.Pointer<CBLBlob> CBLDart_CBLBlob_CreateWithData(
  ffi.Pointer<ffi.Void> contentTypeBuf,
  int contentTypeSize,
  ffi.Pointer<ffi.Void> contentBuf,
  int contentSize,
);

@ffi.Native<NativeCBLDart_CBLBlob_CreateWithStream>(isLeaf: true)
external ffi.Pointer<CBLBlob> CBLDart_CBLBlob_CreateWithStream(
  ffi.Pointer<ffi.Void> contentTypeBuf,
  int contentTypeSize,
  ffi.Pointer<CBLBlobWriteStream> stream,
);

@ffi.Native<NativeCBLDart_CBLEndpoint_CreateWithURL>(isLeaf: true)
external ffi.Pointer<CBLEndpoint> CBLDart_CBLEndpoint_CreateWithURL(
  ffi.Pointer<ffi.Void> urlBuf,
  int urlSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLAuth_CreatePassword>(isLeaf: true)
external ffi.Pointer<CBLAuthenticator> CBLDart_CBLAuth_CreatePassword(
  ffi.Pointer<ffi.Void> userBuf,
  int userSize,
  ffi.Pointer<ffi.Void> pwBuf,
  int pwSize,
);

@ffi.Native<NativeCBLDart_CBLAuth_CreateSession>(isLeaf: true)
external ffi.Pointer<CBLAuthenticator> CBLDart_CBLAuth_CreateSession(
  ffi.Pointer<ffi.Void> sidBuf,
  int sidSize,
  ffi.Pointer<ffi.Void> cnBuf,
  int cnSize,
);

@ffi.Native<NativeCBLDart_CBLReplicator_IsDocumentPending>(isLeaf: true)
external bool CBLDart_CBLReplicator_IsDocumentPending(
  ffi.Pointer<CBLReplicator> replicator,
  ffi.Pointer<ffi.Void> docIDBuf,
  int docIDSize,
  ffi.Pointer<CBLCollection> collection,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLReplicator_Create>(isLeaf: true)
external ffi.Pointer<CBLReplicator> CBLDart_CBLReplicator_Create(
  ffi.Pointer<CBLDart_ReplicatorConfiguration> config,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLReplicator_Release>(isLeaf: true)
external void CBLDart_CBLReplicator_Release(
  ffi.Pointer<CBLReplicator> replicator,
);

@ffi.Native<NativeCBLDart_CBLReplicator_AddChangeListener>(isLeaf: true)
external void CBLDart_CBLReplicator_AddChangeListener(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<CBLReplicator> replicator,
  CBLDart_AsyncCallback listenerId,
);

@ffi.Native<NativeCBLDart_CBLReplicator_AddDocumentReplicationListener>(
  isLeaf: true,
)
external void CBLDart_CBLReplicator_AddDocumentReplicationListener(
  ffi.Pointer<CBLDatabase> db,
  ffi.Pointer<CBLReplicator> replicator,
  CBLDart_AsyncCallback listenerId,
);

@ffi.Native<NativeCBLDart_CBLURLEndpointListener_Create>()
external ffi.Pointer<CBLURLEndpointListener>
CBLDart_CBLURLEndpointListener_Create(
  ffi.Pointer<ffi.Pointer<CBLCollection>> collections,
  int collectionCount,
  int port,
  ffi.Pointer<ffi.Void> networkInterfaceBuf,
  int networkInterfaceSize,
  bool disableTLS,
  ffi.Pointer<CBLTLSIdentity> tlsIdentity,
  ffi.Pointer<CBLListenerAuthenticator> authenticator,
  bool enableDeltaSync,
  bool readOnly,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLLog_SetFileSinkV2>(isLeaf: true)
external void CBLDart_CBLLog_SetFileSinkV2(
  imp$1.DartCBLLogLevel level,
  ffi.Pointer<ffi.Void> dirBuf,
  int dirSize,
  int maxKeptFiles,
  int maxSize,
  bool usePlaintext,
);

@ffi.Native<NativeCBLDart_CBLCert_SubjectNameComponent>(isLeaf: true)
external FLSliceResult CBLDart_CBLCert_SubjectNameComponent(
  ffi.Pointer<CBLCert> cert,
  ffi.Pointer<ffi.Void> keyBuf,
  int keySize,
);

@ffi.Native<NativeCBLDart_CBLKeyPair_CreateWithPrivateKeyData>(isLeaf: true)
external ffi.Pointer<CBLKeyPair> CBLDart_CBLKeyPair_CreateWithPrivateKeyData(
  ffi.Pointer<ffi.Void> pkBuf,
  int pkSize,
  ffi.Pointer<ffi.Void> pwBuf,
  int pwSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLTLSIdentity_CreateIdentity>(isLeaf: true)
external ffi.Pointer<CBLTLSIdentity> CBLDart_CBLTLSIdentity_CreateIdentity(
  int keyUsages,
  imp$1.FLDict attrs,
  int validityMs,
  ffi.Pointer<ffi.Void> labelBuf,
  int labelSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLTLSIdentity_IdentityWithLabel>(isLeaf: true)
external ffi.Pointer<CBLTLSIdentity> CBLDart_CBLTLSIdentity_IdentityWithLabel(
  ffi.Pointer<ffi.Void> labelBuf,
  int labelSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDart_CBLTLSIdentity_DeleteIdentityWithLabel>(isLeaf: true)
external bool CBLDart_CBLTLSIdentity_DeleteIdentityWithLabel(
  ffi.Pointer<ffi.Void> labelBuf,
  int labelSize,
  ffi.Pointer<CBLError> errorOut,
);

@ffi.Native<NativeCBLDartKeyPair_CreateWithExternalKey>()
external ffi.Pointer<CBLKeyPair> CBLDartKeyPair_CreateWithExternalKey(
  int keySizeInBits,
  Object delegate,
  CBLDartExternalKeyPublicKeyData publicKeyData,
  CBLDartExternalKeyDecrypt decrypt,
  CBLDartExternalKeySign sign,
  ffi.Pointer<CBLError> outError,
);

@ffi.Native<NativeCBLDart_ListenerPasswordAuthCallbackTrampoline>()
external bool CBLDart_ListenerPasswordAuthCallbackTrampoline(
  ffi.Pointer<ffi.Void> context,
  imp$1.FLString username,
  imp$1.FLString password,
);

@ffi.Native<NativeCBLDart_ListenerCertAuthCallbackTrampoline>()
external bool CBLDart_ListenerCertAuthCallbackTrampoline(
  ffi.Pointer<ffi.Void> context,
  ffi.Pointer<CBLCert> cert,
);

const addresses = _SymbolAddresses();

class _SymbolAddresses {
  const _SymbolAddresses();
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_FLSliceResult_ReleaseByBuf>>
  get CBLDart_FLSliceResult_ReleaseByBuf =>
      ffi.Native.addressOf(self.CBLDart_FLSliceResult_ReleaseByBuf);
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_KnownSharedKeys_Delete>>
  get CBLDart_KnownSharedKeys_Delete =>
      ffi.Native.addressOf(self.CBLDart_KnownSharedKeys_Delete);
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_FLDictIterator_Delete>>
  get CBLDart_FLDictIterator_Delete =>
      ffi.Native.addressOf(self.CBLDart_FLDictIterator_Delete);
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_FLArrayIterator_Delete>>
  get CBLDart_FLArrayIterator_Delete =>
      ffi.Native.addressOf(self.CBLDart_FLArrayIterator_Delete);
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_AsyncCallback_Delete>>
  get CBLDart_AsyncCallback_Delete =>
      ffi.Native.addressOf(self.CBLDart_AsyncCallback_Delete);
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_CBLDatabase_Release>>
  get CBLDart_CBLDatabase_Release =>
      ffi.Native.addressOf(self.CBLDart_CBLDatabase_Release);
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_PredictiveModel_Delete>>
  get CBLDart_PredictiveModel_Delete =>
      ffi.Native.addressOf(self.CBLDart_PredictiveModel_Delete);
  ffi.Pointer<ffi.NativeFunction<NativeCBLDart_CBLReplicator_Release>>
  get CBLDart_CBLReplicator_Release =>
      ffi.Native.addressOf(self.CBLDart_CBLReplicator_Release);
  ffi.Pointer<
    ffi.NativeFunction<NativeCBLDart_ListenerPasswordAuthCallbackTrampoline>
  >
  get CBLDart_ListenerPasswordAuthCallbackTrampoline =>
      ffi.Native.addressOf(self.CBLDart_ListenerPasswordAuthCallbackTrampoline);
  ffi.Pointer<
    ffi.NativeFunction<NativeCBLDart_ListenerCertAuthCallbackTrampoline>
  >
  get CBLDart_ListenerCertAuthCallbackTrampoline =>
      ffi.Native.addressOf(self.CBLDart_ListenerCertAuthCallbackTrampoline);
}

typedef NativeCBLDart_FLSliceResult_RetainByBuf =
    ffi.Void Function(ffi.Pointer<ffi.Void> buf);
typedef DartCBLDart_FLSliceResult_RetainByBuf =
    void Function(ffi.Pointer<ffi.Void> buf);
typedef NativeCBLDart_FLSliceResult_ReleaseByBuf =
    ffi.Void Function(ffi.Pointer<ffi.Void> buf);
typedef DartCBLDart_FLSliceResult_ReleaseByBuf =
    void Function(ffi.Pointer<ffi.Void> buf);
typedef NativeCBLDart_FLSlice_Equal =
    ffi.Bool Function(
      ffi.Pointer<ffi.Void> aBuf,
      ffi.Size aSize,
      ffi.Pointer<ffi.Void> bBuf,
      ffi.Size bSize,
    );
typedef DartCBLDart_FLSlice_Equal =
    bool Function(
      ffi.Pointer<ffi.Void> aBuf,
      int aSize,
      ffi.Pointer<ffi.Void> bBuf,
      int bSize,
    );
typedef NativeCBLDart_FLSlice_Compare =
    ffi.Int Function(
      ffi.Pointer<ffi.Void> aBuf,
      ffi.Size aSize,
      ffi.Pointer<ffi.Void> bBuf,
      ffi.Size bSize,
    );
typedef DartCBLDart_FLSlice_Compare =
    int Function(
      ffi.Pointer<ffi.Void> aBuf,
      int aSize,
      ffi.Pointer<ffi.Void> bBuf,
      int bSize,
    );
typedef FLSliceResult = imp$1.FLSliceResult;
typedef NativeCBLDart_FLSlice_Copy =
    FLSliceResult Function(ffi.Pointer<ffi.Void> buf, ffi.Size size);
typedef DartCBLDart_FLSlice_Copy =
    FLSliceResult Function(ffi.Pointer<ffi.Void> buf, int size);
typedef NativeCBLDart_FLData_Dump =
    imp$1.FLStringResult Function(
      ffi.Pointer<ffi.Void> dataBuf,
      ffi.Size dataSize,
    );
typedef DartCBLDart_FLData_Dump =
    imp$1.FLStringResult Function(ffi.Pointer<ffi.Void> dataBuf, int dataSize);
typedef NativeCBLDart_FLValue_FromData =
    imp$1.FLValue Function(
      ffi.Pointer<ffi.Void> buf,
      ffi.Size size,
      ffi.Int trust,
    );
typedef DartCBLDart_FLValue_FromData =
    imp$1.FLValue Function(ffi.Pointer<ffi.Void> buf, int size, int trust);
typedef NativeCBLDart_FLDoc_FromResultData =
    imp$1.FLDoc Function(
      ffi.Pointer<ffi.Void> dataBuf,
      ffi.Size dataSize,
      ffi.Int trust,
      imp$1.FLSharedKeys sharedKeys,
      ffi.Pointer<ffi.Void> externBuf,
      ffi.Size externSize,
    );
typedef DartCBLDart_FLDoc_FromResultData =
    imp$1.FLDoc Function(
      ffi.Pointer<ffi.Void> dataBuf,
      int dataSize,
      int trust,
      imp$1.FLSharedKeys sharedKeys,
      ffi.Pointer<ffi.Void> externBuf,
      int externSize,
    );

sealed class FLError {
  static const kFLNoError = 0;
  static const kFLMemoryError = 1;
  static const kFLOutOfRange = 2;
  static const kFLInvalidData = 3;
  static const kFLEncodeError = 4;
  static const kFLJSONError = 5;
  static const kFLUnknownValue = 6;
  static const kFLInternalError = 7;
  static const kFLNotFound = 8;
  static const kFLSharedKeysStateError = 9;
  static const kFLPOSIXError = 10;
  static const kFLUnsupported = 11;
}

typedef NativeCBLDart_FLDoc_FromJSON =
    imp$1.FLDoc Function(
      ffi.Pointer<ffi.Void> jsonBuf,
      ffi.Size jsonSize,
      ffi.Pointer<ffi.UnsignedInt> outError,
    );
typedef DartCBLDart_FLDoc_FromJSON =
    imp$1.FLDoc Function(
      ffi.Pointer<ffi.Void> jsonBuf,
      int jsonSize,
      ffi.Pointer<ffi.UnsignedInt> outError,
    );
typedef NativeCBLDart_FLDict_Get =
    imp$1.FLValue Function(
      imp$1.FLDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_FLDict_Get =
    imp$1.FLValue Function(
      imp$1.FLDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef FLDictKey = imp$1.FLDictKey;
typedef NativeCBLDart_FLDictKey_Init =
    FLDictKey Function(ffi.Pointer<ffi.Void> keyBuf, ffi.Size keySize);
typedef DartCBLDart_FLDictKey_Init =
    FLDictKey Function(ffi.Pointer<ffi.Void> keyBuf, int keySize);
typedef NativeCBLDart_FLMutableDict_Set =
    imp$1.FLSlot Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_FLMutableDict_Set =
    imp$1.FLSlot Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef NativeCBLDart_FLMutableDict_Remove =
    ffi.Void Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_FLMutableDict_Remove =
    void Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef NativeCBLDart_FLMutableDict_GetMutableArray =
    imp$1.FLMutableArray Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_FLMutableDict_GetMutableArray =
    imp$1.FLMutableArray Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef NativeCBLDart_FLMutableDict_GetMutableDict =
    imp$1.FLMutableDict Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_FLMutableDict_GetMutableDict =
    imp$1.FLMutableDict Function(
      imp$1.FLMutableDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef NativeCBLDart_FLSlot_SetString =
    ffi.Void Function(
      imp$1.FLSlot slot,
      ffi.Pointer<ffi.Void> valueBuf,
      ffi.Size valueSize,
    );
typedef DartCBLDart_FLSlot_SetString =
    void Function(
      imp$1.FLSlot slot,
      ffi.Pointer<ffi.Void> valueBuf,
      int valueSize,
    );
typedef NativeCBLDart_FLSlot_SetData =
    ffi.Void Function(
      imp$1.FLSlot slot,
      ffi.Pointer<ffi.Void> dataBuf,
      ffi.Size dataSize,
    );
typedef DartCBLDart_FLSlot_SetData =
    void Function(
      imp$1.FLSlot slot,
      ffi.Pointer<ffi.Void> dataBuf,
      int dataSize,
    );

final class KnownSharedKeys extends ffi.Opaque {}

typedef NativeCBLDart_KnownSharedKeys_New =
    ffi.Pointer<KnownSharedKeys> Function();
typedef DartCBLDart_KnownSharedKeys_New =
    ffi.Pointer<KnownSharedKeys> Function();
typedef NativeCBLDart_KnownSharedKeys_Delete =
    ffi.Void Function(ffi.Pointer<KnownSharedKeys> keys);
typedef DartCBLDart_KnownSharedKeys_Delete =
    void Function(ffi.Pointer<KnownSharedKeys> keys);

final class CBLDart_LoadedDictKey extends ffi.Struct {
  @ffi.Bool()
  external bool isKnownSharedKey;

  @ffi.Int()
  external int sharedKey;

  external ffi.Pointer<ffi.Void> stringBuf;

  @ffi.Size()
  external int stringSize;

  external imp$1.FLValue value;
}

typedef FLSlice = imp$1.FLSlice;

final class CBLDart_LoadedFLValue extends ffi.Struct {
  @ffi.Bool()
  external bool exists;

  @ffi.Int8()
  external int type;

  @ffi.Bool()
  external bool isInteger;

  @ffi.Uint32()
  external int collectionSize;

  @ffi.Bool()
  external bool asBool;

  @ffi.Int64()
  external int asInt;

  @ffi.Double()
  external double asDouble;

  external ffi.Pointer<ffi.Void> stringBuf;

  @ffi.Size()
  external int stringSize;

  external FLSlice asData;

  external imp$1.FLValue value;
}

typedef NativeCBLDart_GetLoadedFLValue =
    ffi.Void Function(
      imp$1.FLValue value,
      ffi.Pointer<CBLDart_LoadedFLValue> out,
    );
typedef DartCBLDart_GetLoadedFLValue =
    void Function(imp$1.FLValue value, ffi.Pointer<CBLDart_LoadedFLValue> out);
typedef NativeCBLDart_FLArray_GetLoadedFLValue =
    ffi.Void Function(
      imp$1.FLArray array,
      ffi.Uint32 index,
      ffi.Pointer<CBLDart_LoadedFLValue> out,
    );
typedef DartCBLDart_FLArray_GetLoadedFLValue =
    void Function(
      imp$1.FLArray array,
      int index,
      ffi.Pointer<CBLDart_LoadedFLValue> out,
    );
typedef NativeCBLDart_FLDict_GetLoadedFLValue =
    ffi.Void Function(
      imp$1.FLDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
      ffi.Pointer<CBLDart_LoadedFLValue> out,
    );
typedef DartCBLDart_FLDict_GetLoadedFLValue =
    void Function(
      imp$1.FLDict dict,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
      ffi.Pointer<CBLDart_LoadedFLValue> out,
    );

final class CBLDart_FLDictIterator extends ffi.Opaque {}

typedef NativeCBLDart_FLDictIterator_Begin =
    ffi.Pointer<CBLDart_FLDictIterator> Function(
      imp$1.FLDict dict,
      ffi.Pointer<KnownSharedKeys> knownSharedKeys,
      ffi.Pointer<CBLDart_LoadedDictKey> keyOut,
      ffi.Pointer<CBLDart_LoadedFLValue> valueOut,
      ffi.Bool deleteOnDone,
      ffi.Bool preLoad,
    );
typedef DartCBLDart_FLDictIterator_Begin =
    ffi.Pointer<CBLDart_FLDictIterator> Function(
      imp$1.FLDict dict,
      ffi.Pointer<KnownSharedKeys> knownSharedKeys,
      ffi.Pointer<CBLDart_LoadedDictKey> keyOut,
      ffi.Pointer<CBLDart_LoadedFLValue> valueOut,
      bool deleteOnDone,
      bool preLoad,
    );
typedef NativeCBLDart_FLDictIterator_Delete =
    ffi.Void Function(ffi.Pointer<CBLDart_FLDictIterator> iterator);
typedef DartCBLDart_FLDictIterator_Delete =
    void Function(ffi.Pointer<CBLDart_FLDictIterator> iterator);
typedef NativeCBLDart_FLDictIterator_Next =
    ffi.Bool Function(ffi.Pointer<CBLDart_FLDictIterator> iterator);
typedef DartCBLDart_FLDictIterator_Next =
    bool Function(ffi.Pointer<CBLDart_FLDictIterator> iterator);

final class CBLDart_FLArrayIterator extends ffi.Opaque {}

typedef NativeCBLDart_FLArrayIterator_Begin =
    ffi.Pointer<CBLDart_FLArrayIterator> Function(
      imp$1.FLArray array,
      ffi.Pointer<CBLDart_LoadedFLValue> valueOut,
      ffi.Bool deleteOnDone,
    );
typedef DartCBLDart_FLArrayIterator_Begin =
    ffi.Pointer<CBLDart_FLArrayIterator> Function(
      imp$1.FLArray array,
      ffi.Pointer<CBLDart_LoadedFLValue> valueOut,
      bool deleteOnDone,
    );
typedef NativeCBLDart_FLArrayIterator_Delete =
    ffi.Void Function(ffi.Pointer<CBLDart_FLArrayIterator> iterator);
typedef DartCBLDart_FLArrayIterator_Delete =
    void Function(ffi.Pointer<CBLDart_FLArrayIterator> iterator);
typedef NativeCBLDart_FLArrayIterator_Next =
    ffi.Bool Function(ffi.Pointer<CBLDart_FLArrayIterator> iterator);
typedef DartCBLDart_FLArrayIterator_Next =
    bool Function(ffi.Pointer<CBLDart_FLArrayIterator> iterator);
typedef NativeCBLDart_FLEncoder_WriteArrayValue =
    ffi.Bool Function(
      imp$1.FLEncoder encoder,
      imp$1.FLArray array,
      ffi.Uint32 index,
    );
typedef DartCBLDart_FLEncoder_WriteArrayValue =
    bool Function(imp$1.FLEncoder encoder, imp$1.FLArray array, int index);
typedef NativeCBLDart_FLEncoder_WriteString =
    ffi.Bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> strBuf,
      ffi.Size strSize,
    );
typedef DartCBLDart_FLEncoder_WriteString =
    bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> strBuf,
      int strSize,
    );
typedef NativeCBLDart_FLEncoder_WriteKey =
    ffi.Bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_FLEncoder_WriteKey =
    bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef NativeCBLDart_FLEncoder_WriteData =
    ffi.Bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> dataBuf,
      ffi.Size dataSize,
    );
typedef DartCBLDart_FLEncoder_WriteData =
    bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> dataBuf,
      int dataSize,
    );
typedef NativeCBLDart_FLEncoder_ConvertJSON =
    ffi.Bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> jsonBuf,
      ffi.Size jsonSize,
    );
typedef DartCBLDart_FLEncoder_ConvertJSON =
    bool Function(
      imp$1.FLEncoder encoder,
      ffi.Pointer<ffi.Void> jsonBuf,
      int jsonSize,
    );
typedef NativeCBLDart_CpuSupportsAVX2 = ffi.Bool Function();
typedef DartCBLDart_CpuSupportsAVX2 = bool Function();
typedef NativeCBLDart_IsEnterprise = ffi.Bool Function();
typedef DartCBLDart_IsEnterprise = bool Function();

sealed class CBLDartInitializeResult {
  static const CBLDartInitializeResult_kSuccess = 0;
  static const CBLDartInitializeResult_kIncompatibleDartVM = 1;
  static const CBLDartInitializeResult_kCBLInitError = 2;
}

typedef CBLError = imp$1.CBLError;
typedef NativeCBLDart_Initialize =
    ffi.UnsignedInt Function(
      ffi.Pointer<ffi.Void> dartInitializeDlData,
      ffi.Pointer<ffi.Void> cblInitContext,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_Initialize =
    int Function(
      ffi.Pointer<ffi.Void> dartInitializeDlData,
      ffi.Pointer<ffi.Void> cblInitContext,
      ffi.Pointer<CBLError> errorOut,
    );

final class _CBLDart_AsyncCallback extends ffi.Opaque {}

typedef CBLDart_AsyncCallback = ffi.Pointer<_CBLDart_AsyncCallback>;
typedef Dart_Port = ffi.Int64;
typedef DartDart_Port = int;
typedef NativeCBLDart_AsyncCallback_New =
    CBLDart_AsyncCallback Function(
      ffi.Uint32 id,
      Dart_Port sendPort,
      ffi.Bool debug,
    );
typedef DartCBLDart_AsyncCallback_New =
    CBLDart_AsyncCallback Function(int id, int sendPort, bool debug);
typedef NativeCBLDart_AsyncCallback_Delete =
    ffi.Void Function(CBLDart_AsyncCallback callback);
typedef DartCBLDart_AsyncCallback_Delete =
    void Function(CBLDart_AsyncCallback callback);
typedef NativeCBLDart_AsyncCallback_Close =
    ffi.Void Function(CBLDart_AsyncCallback callback);
typedef DartCBLDart_AsyncCallback_Close =
    void Function(CBLDart_AsyncCallback callback);
typedef NativeCBLDart_AsyncCallback_CallForTest =
    ffi.Void Function(CBLDart_AsyncCallback callback, ffi.Int64 argument);
typedef DartCBLDart_AsyncCallback_CallForTest =
    void Function(CBLDart_AsyncCallback callback, int argument);

final class _CBLDart_Completer extends ffi.Opaque {}

typedef CBLDart_Completer = ffi.Pointer<_CBLDart_Completer>;
typedef NativeCBLDart_Completer_Complete =
    ffi.Void Function(CBLDart_Completer completer, ffi.Uint64 result);
typedef DartCBLDart_Completer_Complete =
    void Function(CBLDart_Completer completer, int result);
typedef CBLDart_IsolateId = ffi.Int;
typedef DartCBLDart_IsolateId = int;
typedef NativeCBLDart_AllocateIsolateId = CBLDart_IsolateId Function();
typedef DartCBLDart_AllocateIsolateId = int Function();
typedef NativeCBLDart_SetCurrentIsolateId =
    ffi.Void Function(CBLDart_IsolateId isolateId);
typedef DartCBLDart_SetCurrentIsolateId = void Function(int isolateId);
typedef NativeCBLDart_GetCurrentIsolateId = CBLDart_IsolateId Function();
typedef DartCBLDart_GetCurrentIsolateId = int Function();
typedef NativeCBLDart_CBLLog_AddCallback =
    ffi.Void Function(CBLDart_AsyncCallback callback, imp$1.CBLLogLevel level);
typedef DartCBLDart_CBLLog_AddCallback =
    void Function(CBLDart_AsyncCallback callback, imp$1.DartCBLLogLevel level);
typedef NativeCBLDart_CBLLog_SetCallbackLevel =
    ffi.Void Function(CBLDart_AsyncCallback callback, imp$1.CBLLogLevel level);
typedef DartCBLDart_CBLLog_SetCallbackLevel =
    void Function(CBLDart_AsyncCallback callback, imp$1.DartCBLLogLevel level);
typedef CBLFileLogSink = imp$1.CBLFileLogSink;
typedef NativeCBLDart_CBLLog_SetFileSink =
    ffi.Void Function(ffi.Pointer<CBLFileLogSink> sink);
typedef DartCBLDart_CBLLog_SetFileSink =
    void Function(ffi.Pointer<CBLFileLogSink> sink);
typedef NativeCBLDart_CBLLog_GetFileSink =
    ffi.Pointer<CBLFileLogSink> Function();
typedef DartCBLDart_CBLLog_GetFileSink = ffi.Pointer<CBLFileLogSink> Function();
typedef NativeCBLDart_CBL_LogMessage =
    ffi.Void Function(
      imp$1.CBLLogDomain domain,
      imp$1.CBLLogLevel level,
      ffi.Pointer<ffi.Void> msgBuf,
      ffi.Size msgSize,
    );
typedef DartCBLDart_CBL_LogMessage =
    void Function(
      imp$1.DartCBLLogDomain domain,
      imp$1.DartCBLLogLevel level,
      ffi.Pointer<ffi.Void> msgBuf,
      int msgSize,
    );
typedef NativeCBLDart_CBL_EnableVectorSearch =
    ffi.Bool Function(
      ffi.Pointer<ffi.Void> dirBuf,
      ffi.Size dirSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBL_EnableVectorSearch =
    bool Function(
      ffi.Pointer<ffi.Void> dirBuf,
      int dirSize,
      ffi.Pointer<CBLError> errorOut,
    );

final class CBLDart_CBLEncryptionKey extends ffi.Struct {
  @ffi.Uint32()
  external int algorithm;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> bytes;
}

final class CBLDart_CBLDatabaseConfiguration extends ffi.Struct {
  external ffi.Pointer<ffi.Void> directoryBuf;

  @ffi.Size()
  external int directorySize;

  external CBLDart_CBLEncryptionKey encryptionKey;

  @ffi.Bool()
  external bool fullSync;
}

typedef NativeCBLDart_CBLDatabaseConfiguration_Default =
    CBLDart_CBLDatabaseConfiguration Function();
typedef DartCBLDart_CBLDatabaseConfiguration_Default =
    CBLDart_CBLDatabaseConfiguration Function();
typedef NativeCBLDart_CBL_CopyDatabase =
    ffi.Bool Function(
      ffi.Pointer<ffi.Void> fromPathBuf,
      ffi.Size fromPathSize,
      ffi.Pointer<ffi.Void> toNameBuf,
      ffi.Size toNameSize,
      ffi.Pointer<CBLDart_CBLDatabaseConfiguration> config,
      ffi.Pointer<CBLError> outError,
    );
typedef DartCBLDart_CBL_CopyDatabase =
    bool Function(
      ffi.Pointer<ffi.Void> fromPathBuf,
      int fromPathSize,
      ffi.Pointer<ffi.Void> toNameBuf,
      int toNameSize,
      ffi.Pointer<CBLDart_CBLDatabaseConfiguration> config,
      ffi.Pointer<CBLError> outError,
    );
typedef CBLDatabase = imp$1.CBLDatabase;
typedef NativeCBLDart_CBLDatabase_Open =
    ffi.Pointer<CBLDatabase> Function(
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      ffi.Pointer<CBLDart_CBLDatabaseConfiguration> config,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLDatabase_Open =
    ffi.Pointer<CBLDatabase> Function(
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      ffi.Pointer<CBLDart_CBLDatabaseConfiguration> config,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLDatabase_Release =
    ffi.Void Function(ffi.Pointer<CBLDatabase> database);
typedef DartCBLDart_CBLDatabase_Release =
    void Function(ffi.Pointer<CBLDatabase> database);
typedef NativeCBLDart_CBLDatabase_Close =
    ffi.Bool Function(
      ffi.Pointer<CBLDatabase> database,
      ffi.Bool andDelete,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLDatabase_Close =
    bool Function(
      ffi.Pointer<CBLDatabase> database,
      bool andDelete,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBL_DeleteDatabase =
    ffi.Bool Function(
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      ffi.Pointer<ffi.Void> inDirBuf,
      ffi.Size inDirSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBL_DeleteDatabase =
    bool Function(
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      ffi.Pointer<ffi.Void> inDirBuf,
      int inDirSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBL_DatabaseExists =
    ffi.Bool Function(
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      ffi.Pointer<ffi.Void> inDirBuf,
      ffi.Size inDirSize,
    );
typedef DartCBLDart_CBL_DatabaseExists =
    bool Function(
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      ffi.Pointer<ffi.Void> inDirBuf,
      int inDirSize,
    );
typedef CBLEncryptionKey = imp$1.CBLEncryptionKey;
typedef NativeCBLDart_CBLEncryptionKey_FromPassword =
    ffi.Bool Function(
      ffi.Pointer<CBLEncryptionKey> key,
      ffi.Pointer<ffi.Void> pwBuf,
      ffi.Size pwSize,
    );
typedef DartCBLDart_CBLEncryptionKey_FromPassword =
    bool Function(
      ffi.Pointer<CBLEncryptionKey> key,
      ffi.Pointer<ffi.Void> pwBuf,
      int pwSize,
    );
typedef CBLScope = imp$1.CBLScope;
typedef NativeCBLDart_CBLDatabase_Scope =
    ffi.Pointer<CBLScope> Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLDatabase_Scope =
    ffi.Pointer<CBLScope> Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef CBLCollection = imp$1.CBLCollection;
typedef NativeCBLDart_CBLScope_Collection =
    ffi.Pointer<CBLCollection> Function(
      ffi.Pointer<CBLScope> scope,
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLScope_Collection =
    ffi.Pointer<CBLCollection> Function(
      ffi.Pointer<CBLScope> scope,
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLDatabase_CreateCollection =
    ffi.Pointer<CBLCollection> Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<ffi.Void> colNameBuf,
      ffi.Size colNameSize,
      ffi.Pointer<ffi.Void> scopeNameBuf,
      ffi.Size scopeNameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLDatabase_CreateCollection =
    ffi.Pointer<CBLCollection> Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<ffi.Void> colNameBuf,
      int colNameSize,
      ffi.Pointer<ffi.Void> scopeNameBuf,
      int scopeNameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLDatabase_DeleteCollection =
    ffi.Bool Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<ffi.Void> colNameBuf,
      ffi.Size colNameSize,
      ffi.Pointer<ffi.Void> scopeNameBuf,
      ffi.Size scopeNameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLDatabase_DeleteCollection =
    bool Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<ffi.Void> colNameBuf,
      int colNameSize,
      ffi.Pointer<ffi.Void> scopeNameBuf,
      int scopeNameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef CBLDocument = imp$1.CBLDocument;
typedef NativeCBLDart_CBLCollection_GetDocument =
    ffi.Pointer<CBLDocument> Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      ffi.Size docIDSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLCollection_GetDocument =
    ffi.Pointer<CBLDocument> Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      int docIDSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLCollection_PurgeDocumentByID =
    ffi.Bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      ffi.Size docIDSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLCollection_PurgeDocumentByID =
    bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      int docIDSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLCollection_GetDocumentExpiration =
    imp$1.CBLTimestamp Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      ffi.Size docIDSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLCollection_GetDocumentExpiration =
    imp$1.DartCBLTimestamp Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      int docIDSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLCollection_SetDocumentExpiration =
    ffi.Bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      ffi.Size docIDSize,
      imp$1.CBLTimestamp expiration,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLCollection_SetDocumentExpiration =
    bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      int docIDSize,
      imp$1.DartCBLTimestamp expiration,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLCollection_AddDocumentChangeListener =
    ffi.Void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      ffi.Size docIDSize,
      CBLDart_AsyncCallback listener,
    );
typedef DartCBLDart_CBLCollection_AddDocumentChangeListener =
    void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> docIDBuf,
      int docIDSize,
      CBLDart_AsyncCallback listener,
    );
typedef NativeCBLDart_CBLCollection_AddChangeListener =
    ffi.Void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLCollection> collection,
      CBLDart_AsyncCallback listener,
    );
typedef DartCBLDart_CBLCollection_AddChangeListener =
    void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLCollection> collection,
      CBLDart_AsyncCallback listener,
    );
typedef CBLQueryIndex = imp$1.CBLQueryIndex;
typedef NativeCBLDart_CBLCollection_GetIndex =
    ffi.Pointer<CBLQueryIndex> Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLCollection_GetIndex =
    ffi.Pointer<CBLQueryIndex> Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      ffi.Pointer<CBLError> errorOut,
    );

sealed class CBLDart_IndexType {
  static const kCBLDart_IndexTypeValue = 0;
  static const kCBLDart_IndexTypeFullText = 1;
  static const kCBLDart_IndexTypeVector = 2;
}

final class CBLDart_CBLIndexSpec extends ffi.Struct {
  @ffi.Uint8()
  external int type;

  @imp$1.CBLQueryLanguage()
  external imp$1.DartCBLQueryLanguage expressionLanguage;

  external ffi.Pointer<ffi.Void> expressionsBuf;

  @ffi.Size()
  external int expressionsSize;

  @ffi.Bool()
  external bool ignoreAccents;

  external ffi.Pointer<ffi.Void> languageBuf;

  @ffi.Size()
  external int languageSize;

  @ffi.UnsignedInt()
  external int dimensions;

  @ffi.UnsignedInt()
  external int centroids;

  @ffi.Bool()
  external bool isLazy;

  external ffi.Pointer<ffi.Void> encoding;

  @ffi.Uint32()
  external int metric;

  @ffi.UnsignedInt()
  external int minTrainingSize;

  @ffi.UnsignedInt()
  external int maxTrainingSize;

  @ffi.UnsignedInt()
  external int numProbes;
}

typedef NativeCBLDart_CBLCollection_CreateIndex =
    ffi.Bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      CBLDart_CBLIndexSpec indexSpec,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLCollection_CreateIndex =
    bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      CBLDart_CBLIndexSpec indexSpec,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLCollection_DeleteIndex =
    ffi.Bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLCollection_DeleteIndex =
    bool Function(
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLDocument_CreateWithID =
    ffi.Pointer<CBLDocument> Function(
      ffi.Pointer<ffi.Void> docIDBuf,
      ffi.Size docIDSize,
    );
typedef DartCBLDart_CBLDocument_CreateWithID =
    ffi.Pointer<CBLDocument> Function(
      ffi.Pointer<ffi.Void> docIDBuf,
      int docIDSize,
    );
typedef NativeCBLDart_CBLDocument_SetJSON =
    ffi.Bool Function(
      ffi.Pointer<CBLDocument> doc,
      ffi.Pointer<ffi.Void> jsonBuf,
      ffi.Size jsonSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLDocument_SetJSON =
    bool Function(
      ffi.Pointer<CBLDocument> doc,
      ffi.Pointer<ffi.Void> jsonBuf,
      int jsonSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef CBLQuery = imp$1.CBLQuery;
typedef NativeCBLDart_CBLDatabase_CreateQuery =
    ffi.Pointer<CBLQuery> Function(
      ffi.Pointer<CBLDatabase> db,
      imp$1.CBLQueryLanguage language,
      ffi.Pointer<ffi.Void> queryBuf,
      ffi.Size querySize,
      ffi.Pointer<ffi.Int> errorPos,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLDatabase_CreateQuery =
    ffi.Pointer<CBLQuery> Function(
      ffi.Pointer<CBLDatabase> db,
      imp$1.DartCBLQueryLanguage language,
      ffi.Pointer<ffi.Void> queryBuf,
      int querySize,
      ffi.Pointer<ffi.Int> errorPos,
      ffi.Pointer<CBLError> errorOut,
    );
typedef CBLListenerToken = imp$1.CBLListenerToken;
typedef NativeCBLDart_CBLQuery_AddChangeListener =
    ffi.Pointer<CBLListenerToken> Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLQuery> query,
      CBLDart_AsyncCallback listener,
    );
typedef DartCBLDart_CBLQuery_AddChangeListener =
    ffi.Pointer<CBLListenerToken> Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLQuery> query,
      CBLDart_AsyncCallback listener,
    );
typedef CBLResultSet = imp$1.CBLResultSet;
typedef NativeCBLDart_CBLResultSet_ValueForKey =
    imp$1.FLValue Function(
      ffi.Pointer<CBLResultSet> resultSet,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_CBLResultSet_ValueForKey =
    imp$1.FLValue Function(
      ffi.Pointer<CBLResultSet> resultSet,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef CBLDart_PredictiveModel_PredictionSyncFunction =
    imp$1.FLMutableDict Function(imp$1.FLDict input);
typedef CBLDart_PredictiveModel_PredictionSync =
    ffi.Pointer<
      ffi.NativeFunction<CBLDart_PredictiveModel_PredictionSyncFunction>
    >;
typedef CBLDart_PredictiveModel_PredictionAsyncFunction =
    ffi.Void Function(imp$1.FLDict input, CBLDart_Completer completer);
typedef DartCBLDart_PredictiveModel_PredictionAsyncFunction =
    void Function(imp$1.FLDict input, CBLDart_Completer completer);
typedef CBLDart_PredictiveModel_PredictionAsync =
    ffi.Pointer<
      ffi.NativeFunction<CBLDart_PredictiveModel_PredictionAsyncFunction>
    >;
typedef CBLDart_PredictiveModel_UnregisteredFunction = ffi.Void Function();
typedef DartCBLDart_PredictiveModel_UnregisteredFunction = void Function();
typedef CBLDart_PredictiveModel_Unregistered =
    ffi.Pointer<
      ffi.NativeFunction<CBLDart_PredictiveModel_UnregisteredFunction>
    >;

final class _CBLDart_PredictiveModel extends ffi.Opaque {}

typedef CBLDart_PredictiveModel = ffi.Pointer<_CBLDart_PredictiveModel>;
typedef NativeCBLDart_PredictiveModel_New =
    CBLDart_PredictiveModel Function(
      ffi.Pointer<ffi.Void> nameBuf,
      ffi.Size nameSize,
      CBLDart_IsolateId isolateId,
      CBLDart_PredictiveModel_PredictionSync predictionSync,
      CBLDart_PredictiveModel_PredictionAsync predictionAsync,
      CBLDart_PredictiveModel_Unregistered unregistered,
    );
typedef DartCBLDart_PredictiveModel_New =
    CBLDart_PredictiveModel Function(
      ffi.Pointer<ffi.Void> nameBuf,
      int nameSize,
      int isolateId,
      CBLDart_PredictiveModel_PredictionSync predictionSync,
      CBLDart_PredictiveModel_PredictionAsync predictionAsync,
      CBLDart_PredictiveModel_Unregistered unregistered,
    );
typedef NativeCBLDart_PredictiveModel_Delete =
    ffi.Void Function(CBLDart_PredictiveModel model);
typedef DartCBLDart_PredictiveModel_Delete =
    void Function(CBLDart_PredictiveModel model);
typedef NativeCBLDart_CBL_UnregisterPredictiveModel =
    ffi.Void Function(ffi.Pointer<ffi.Void> nameBuf, ffi.Size nameSize);
typedef DartCBLDart_CBL_UnregisterPredictiveModel =
    void Function(ffi.Pointer<ffi.Void> nameBuf, int nameSize);
typedef CBLBlobReadStream = imp$1.CBLBlobReadStream;
typedef NativeCBLDart_CBLBlobReader_Read =
    FLSliceResult Function(
      ffi.Pointer<CBLBlobReadStream> stream,
      ffi.Uint64 bufferSize,
      ffi.Pointer<CBLError> outError,
    );
typedef DartCBLDart_CBLBlobReader_Read =
    FLSliceResult Function(
      ffi.Pointer<CBLBlobReadStream> stream,
      int bufferSize,
      ffi.Pointer<CBLError> outError,
    );
typedef CBLBlob = imp$1.CBLBlob;
typedef NativeCBLDart_CBLBlob_CreateWithData =
    ffi.Pointer<CBLBlob> Function(
      ffi.Pointer<ffi.Void> contentTypeBuf,
      ffi.Size contentTypeSize,
      ffi.Pointer<ffi.Void> contentBuf,
      ffi.Size contentSize,
    );
typedef DartCBLDart_CBLBlob_CreateWithData =
    ffi.Pointer<CBLBlob> Function(
      ffi.Pointer<ffi.Void> contentTypeBuf,
      int contentTypeSize,
      ffi.Pointer<ffi.Void> contentBuf,
      int contentSize,
    );
typedef CBLBlobWriteStream = imp$1.CBLBlobWriteStream;
typedef NativeCBLDart_CBLBlob_CreateWithStream =
    ffi.Pointer<CBLBlob> Function(
      ffi.Pointer<ffi.Void> contentTypeBuf,
      ffi.Size contentTypeSize,
      ffi.Pointer<CBLBlobWriteStream> stream,
    );
typedef DartCBLDart_CBLBlob_CreateWithStream =
    ffi.Pointer<CBLBlob> Function(
      ffi.Pointer<ffi.Void> contentTypeBuf,
      int contentTypeSize,
      ffi.Pointer<CBLBlobWriteStream> stream,
    );
typedef CBLEndpoint = imp$1.CBLEndpoint;
typedef NativeCBLDart_CBLEndpoint_CreateWithURL =
    ffi.Pointer<CBLEndpoint> Function(
      ffi.Pointer<ffi.Void> urlBuf,
      ffi.Size urlSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLEndpoint_CreateWithURL =
    ffi.Pointer<CBLEndpoint> Function(
      ffi.Pointer<ffi.Void> urlBuf,
      int urlSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef CBLAuthenticator = imp$1.CBLAuthenticator;
typedef NativeCBLDart_CBLAuth_CreatePassword =
    ffi.Pointer<CBLAuthenticator> Function(
      ffi.Pointer<ffi.Void> userBuf,
      ffi.Size userSize,
      ffi.Pointer<ffi.Void> pwBuf,
      ffi.Size pwSize,
    );
typedef DartCBLDart_CBLAuth_CreatePassword =
    ffi.Pointer<CBLAuthenticator> Function(
      ffi.Pointer<ffi.Void> userBuf,
      int userSize,
      ffi.Pointer<ffi.Void> pwBuf,
      int pwSize,
    );
typedef NativeCBLDart_CBLAuth_CreateSession =
    ffi.Pointer<CBLAuthenticator> Function(
      ffi.Pointer<ffi.Void> sidBuf,
      ffi.Size sidSize,
      ffi.Pointer<ffi.Void> cnBuf,
      ffi.Size cnSize,
    );
typedef DartCBLDart_CBLAuth_CreateSession =
    ffi.Pointer<CBLAuthenticator> Function(
      ffi.Pointer<ffi.Void> sidBuf,
      int sidSize,
      ffi.Pointer<ffi.Void> cnBuf,
      int cnSize,
    );
typedef CBLReplicator = imp$1.CBLReplicator;
typedef NativeCBLDart_CBLReplicator_IsDocumentPending =
    ffi.Bool Function(
      ffi.Pointer<CBLReplicator> replicator,
      ffi.Pointer<ffi.Void> docIDBuf,
      ffi.Size docIDSize,
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLReplicator_IsDocumentPending =
    bool Function(
      ffi.Pointer<CBLReplicator> replicator,
      ffi.Pointer<ffi.Void> docIDBuf,
      int docIDSize,
      ffi.Pointer<CBLCollection> collection,
      ffi.Pointer<CBLError> errorOut,
    );

final class CBLDart_ProxySettings extends ffi.Struct {
  @imp$1.CBLProxyType()
  external imp$1.DartCBLProxyType type;

  external ffi.Pointer<ffi.Void> hostnameBuf;

  @ffi.Size()
  external int hostnameSize;

  @ffi.Uint16()
  external int port;

  external ffi.Pointer<ffi.Void> usernameBuf;

  @ffi.Size()
  external int usernameSize;

  external ffi.Pointer<ffi.Void> passwordBuf;

  @ffi.Size()
  external int passwordSize;
}

final class CBLDart_ReplicationCollection extends ffi.Struct {
  external ffi.Pointer<CBLCollection> collection;

  external imp$1.FLArray channels;

  external imp$1.FLArray documentIDs;

  external CBLDart_AsyncCallback pushFilter;

  external CBLDart_AsyncCallback pullFilter;

  external CBLDart_AsyncCallback conflictResolver;
}

final class CBLDart_ReplicatorConfiguration extends ffi.Struct {
  external ffi.Pointer<CBLDatabase> database;

  external ffi.Pointer<CBLEndpoint> endpoint;

  @imp$1.CBLReplicatorType()
  external imp$1.DartCBLReplicatorType replicatorType;

  @ffi.Bool()
  external bool continuous;

  @ffi.Bool()
  external bool disableAutoPurge;

  @ffi.UnsignedInt()
  external int maxAttempts;

  @ffi.UnsignedInt()
  external int maxAttemptWaitTime;

  @ffi.UnsignedInt()
  external int heartbeat;

  external ffi.Pointer<CBLAuthenticator> authenticator;

  external ffi.Pointer<CBLDart_ProxySettings> proxy;

  external imp$1.FLDict headers;

  @ffi.Bool()
  external bool acceptOnlySelfSignedServerCertificate;

  external ffi.Pointer<FLSlice> pinnedServerCertificate;

  external ffi.Pointer<FLSlice> trustedRootCertificates;

  external ffi.Pointer<CBLDart_ReplicationCollection> collections;

  @ffi.Size()
  external int collectionsCount;

  @ffi.Bool()
  external bool acceptParentDomainCookies;
}

typedef NativeCBLDart_CBLReplicator_Create =
    ffi.Pointer<CBLReplicator> Function(
      ffi.Pointer<CBLDart_ReplicatorConfiguration> config,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLReplicator_Create =
    ffi.Pointer<CBLReplicator> Function(
      ffi.Pointer<CBLDart_ReplicatorConfiguration> config,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLReplicator_Release =
    ffi.Void Function(ffi.Pointer<CBLReplicator> replicator);
typedef DartCBLDart_CBLReplicator_Release =
    void Function(ffi.Pointer<CBLReplicator> replicator);
typedef NativeCBLDart_CBLReplicator_AddChangeListener =
    ffi.Void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLReplicator> replicator,
      CBLDart_AsyncCallback listenerId,
    );
typedef DartCBLDart_CBLReplicator_AddChangeListener =
    void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLReplicator> replicator,
      CBLDart_AsyncCallback listenerId,
    );
typedef NativeCBLDart_CBLReplicator_AddDocumentReplicationListener =
    ffi.Void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLReplicator> replicator,
      CBLDart_AsyncCallback listenerId,
    );
typedef DartCBLDart_CBLReplicator_AddDocumentReplicationListener =
    void Function(
      ffi.Pointer<CBLDatabase> db,
      ffi.Pointer<CBLReplicator> replicator,
      CBLDart_AsyncCallback listenerId,
    );
typedef CBLURLEndpointListener = imp$1.CBLURLEndpointListener;
typedef CBLTLSIdentity = imp$1.CBLTLSIdentity;
typedef CBLListenerAuthenticator = imp$1.CBLListenerAuthenticator;
typedef NativeCBLDart_CBLURLEndpointListener_Create =
    ffi.Pointer<CBLURLEndpointListener> Function(
      ffi.Pointer<ffi.Pointer<CBLCollection>> collections,
      ffi.Size collectionCount,
      ffi.Uint16 port,
      ffi.Pointer<ffi.Void> networkInterfaceBuf,
      ffi.Size networkInterfaceSize,
      ffi.Bool disableTLS,
      ffi.Pointer<CBLTLSIdentity> tlsIdentity,
      ffi.Pointer<CBLListenerAuthenticator> authenticator,
      ffi.Bool enableDeltaSync,
      ffi.Bool readOnly,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLURLEndpointListener_Create =
    ffi.Pointer<CBLURLEndpointListener> Function(
      ffi.Pointer<ffi.Pointer<CBLCollection>> collections,
      int collectionCount,
      int port,
      ffi.Pointer<ffi.Void> networkInterfaceBuf,
      int networkInterfaceSize,
      bool disableTLS,
      ffi.Pointer<CBLTLSIdentity> tlsIdentity,
      ffi.Pointer<CBLListenerAuthenticator> authenticator,
      bool enableDeltaSync,
      bool readOnly,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLLog_SetFileSinkV2 =
    ffi.Void Function(
      imp$1.CBLLogLevel level,
      ffi.Pointer<ffi.Void> dirBuf,
      ffi.Size dirSize,
      ffi.UnsignedInt maxKeptFiles,
      ffi.Size maxSize,
      ffi.Bool usePlaintext,
    );
typedef DartCBLDart_CBLLog_SetFileSinkV2 =
    void Function(
      imp$1.DartCBLLogLevel level,
      ffi.Pointer<ffi.Void> dirBuf,
      int dirSize,
      int maxKeptFiles,
      int maxSize,
      bool usePlaintext,
    );
typedef CBLCert = imp$1.CBLCert;
typedef NativeCBLDart_CBLCert_SubjectNameComponent =
    FLSliceResult Function(
      ffi.Pointer<CBLCert> cert,
      ffi.Pointer<ffi.Void> keyBuf,
      ffi.Size keySize,
    );
typedef DartCBLDart_CBLCert_SubjectNameComponent =
    FLSliceResult Function(
      ffi.Pointer<CBLCert> cert,
      ffi.Pointer<ffi.Void> keyBuf,
      int keySize,
    );
typedef CBLKeyPair = imp$1.CBLKeyPair;
typedef NativeCBLDart_CBLKeyPair_CreateWithPrivateKeyData =
    ffi.Pointer<CBLKeyPair> Function(
      ffi.Pointer<ffi.Void> pkBuf,
      ffi.Size pkSize,
      ffi.Pointer<ffi.Void> pwBuf,
      ffi.Size pwSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLKeyPair_CreateWithPrivateKeyData =
    ffi.Pointer<CBLKeyPair> Function(
      ffi.Pointer<ffi.Void> pkBuf,
      int pkSize,
      ffi.Pointer<ffi.Void> pwBuf,
      int pwSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLTLSIdentity_CreateIdentity =
    ffi.Pointer<CBLTLSIdentity> Function(
      ffi.Int keyUsages,
      imp$1.FLDict attrs,
      ffi.Int64 validityMs,
      ffi.Pointer<ffi.Void> labelBuf,
      ffi.Size labelSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLTLSIdentity_CreateIdentity =
    ffi.Pointer<CBLTLSIdentity> Function(
      int keyUsages,
      imp$1.FLDict attrs,
      int validityMs,
      ffi.Pointer<ffi.Void> labelBuf,
      int labelSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLTLSIdentity_IdentityWithLabel =
    ffi.Pointer<CBLTLSIdentity> Function(
      ffi.Pointer<ffi.Void> labelBuf,
      ffi.Size labelSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLTLSIdentity_IdentityWithLabel =
    ffi.Pointer<CBLTLSIdentity> Function(
      ffi.Pointer<ffi.Void> labelBuf,
      int labelSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef NativeCBLDart_CBLTLSIdentity_DeleteIdentityWithLabel =
    ffi.Bool Function(
      ffi.Pointer<ffi.Void> labelBuf,
      ffi.Size labelSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef DartCBLDart_CBLTLSIdentity_DeleteIdentityWithLabel =
    bool Function(
      ffi.Pointer<ffi.Void> labelBuf,
      int labelSize,
      ffi.Pointer<CBLError> errorOut,
    );
typedef CBLDartExternalKeyPublicKeyDataFunction =
    ffi.Void Function(
      CBLDart_Completer completer,
      ffi.Pointer<ffi.Void> output,
      ffi.Size outputMaxLen,
      ffi.Pointer<ffi.Size> outputLen,
    );
typedef DartCBLDartExternalKeyPublicKeyDataFunction =
    void Function(
      CBLDart_Completer completer,
      ffi.Pointer<ffi.Void> output,
      int outputMaxLen,
      ffi.Pointer<ffi.Size> outputLen,
    );
typedef CBLDartExternalKeyPublicKeyData =
    ffi.Pointer<ffi.NativeFunction<CBLDartExternalKeyPublicKeyDataFunction>>;
typedef CBLDartExternalKeyDecryptFunction =
    ffi.Void Function(
      CBLDart_Completer completer,
      FLSlice input,
      ffi.Pointer<ffi.Void> output,
      ffi.Size outputMaxLen,
      ffi.Pointer<ffi.Size> outputLen,
    );
typedef DartCBLDartExternalKeyDecryptFunction =
    void Function(
      CBLDart_Completer completer,
      FLSlice input,
      ffi.Pointer<ffi.Void> output,
      int outputMaxLen,
      ffi.Pointer<ffi.Size> outputLen,
    );
typedef CBLDartExternalKeyDecrypt =
    ffi.Pointer<ffi.NativeFunction<CBLDartExternalKeyDecryptFunction>>;
typedef CBLDartExternalKeySignFunction =
    ffi.Void Function(
      CBLDart_Completer completer,
      imp$1.CBLSignatureDigestAlgorithm digestAlgorithm,
      FLSlice inputData,
      ffi.Pointer<ffi.Void> outSignature,
    );
typedef DartCBLDartExternalKeySignFunction =
    void Function(
      CBLDart_Completer completer,
      imp$1.DartCBLSignatureDigestAlgorithm digestAlgorithm,
      FLSlice inputData,
      ffi.Pointer<ffi.Void> outSignature,
    );
typedef CBLDartExternalKeySign =
    ffi.Pointer<ffi.NativeFunction<CBLDartExternalKeySignFunction>>;
typedef NativeCBLDartKeyPair_CreateWithExternalKey =
    ffi.Pointer<CBLKeyPair> Function(
      ffi.Size keySizeInBits,
      ffi.Handle delegate,
      CBLDartExternalKeyPublicKeyData publicKeyData,
      CBLDartExternalKeyDecrypt decrypt,
      CBLDartExternalKeySign sign,
      ffi.Pointer<CBLError> outError,
    );
typedef DartCBLDartKeyPair_CreateWithExternalKey =
    ffi.Pointer<CBLKeyPair> Function(
      int keySizeInBits,
      Object delegate,
      CBLDartExternalKeyPublicKeyData publicKeyData,
      CBLDartExternalKeyDecrypt decrypt,
      CBLDartExternalKeySign sign,
      ffi.Pointer<CBLError> outError,
    );
typedef CBLDartListenerPasswordAuthCallbackFunction =
    ffi.Void Function(
      CBLDart_Completer completer,
      imp$1.FLString username,
      imp$1.FLString password,
    );
typedef DartCBLDartListenerPasswordAuthCallbackFunction =
    void Function(
      CBLDart_Completer completer,
      imp$1.FLString username,
      imp$1.FLString password,
    );
typedef CBLDartListenerPasswordAuthCallback =
    ffi.Pointer<
      ffi.NativeFunction<CBLDartListenerPasswordAuthCallbackFunction>
    >;
typedef NativeCBLDart_ListenerPasswordAuthCallbackTrampoline =
    ffi.Bool Function(
      ffi.Pointer<ffi.Void> context,
      imp$1.FLString username,
      imp$1.FLString password,
    );
typedef DartCBLDart_ListenerPasswordAuthCallbackTrampoline =
    bool Function(
      ffi.Pointer<ffi.Void> context,
      imp$1.FLString username,
      imp$1.FLString password,
    );
typedef CBLDartListenerCertAuthCallbackFunction =
    ffi.Void Function(CBLDart_Completer completer, ffi.Pointer<CBLCert> cert);
typedef DartCBLDartListenerCertAuthCallbackFunction =
    void Function(CBLDart_Completer completer, ffi.Pointer<CBLCert> cert);
typedef CBLDartListenerCertAuthCallback =
    ffi.Pointer<ffi.NativeFunction<CBLDartListenerCertAuthCallbackFunction>>;
typedef NativeCBLDart_ListenerCertAuthCallbackTrampoline =
    ffi.Bool Function(ffi.Pointer<ffi.Void> context, ffi.Pointer<CBLCert> cert);
typedef DartCBLDart_ListenerCertAuthCallbackTrampoline =
    bool Function(ffi.Pointer<ffi.Void> context, ffi.Pointer<CBLCert> cert);

const int kCBLDartInvalidIsolateId = -1;
