on:
  pull_request:
    types:
      - closed

jobs:
  run:
    # Fork PRs don't have access to the secrets, so we don't run the job for them.
    if:
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bencher
        uses: bencherdev/bencher@main
      - name: Archive closed PR branch
        run: |
          bencher archive \
            --project cbl-dart \
            --token '${{ secrets.BENCHER_API_TOKEN }}' \
            --branch "$GITHUB_HEAD_REF"
