name: Benchmark Main Branch

on:
  push:
    branches:
      - main

jobs:
  run:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bencher
        uses: bencherdev/bencher@main

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Setup Melos
        run: dart pub global activate melos

      - name: Bootstrap Dart packages
        shell: bash
        run: ./tools/dev-tools.sh bootstrap

      - name: Setup cbd
        run: melos activate:cbd

      - name: Build native libraries
        shell: bash
        run: ./tools/ci-steps.sh buildNativeLibraries

      - name: Run benchmarks
        working-directory: packages/benchmark
        run: dart run bin/runner.dart

      - name: Upload benchmark results
        working-directory: packages/benchmark
        run: |
          bencher run \
            --project cbl-dart \
            --token '${{ secrets.BENCHER_API_TOKEN }}' \
            --branch main \
            --testbed ubuntu-latest \
            --threshold-measure latency \
            --threshold-test t_test \
            --threshold-max-sample-size 64 \
            --threshold-upper-boundary 0.99 \
            --thresholds-reset \
            --err \
            --adapter json \
            --file results.json \
            --github-actions '${{ secrets.GITHUB_TOKEN }}'
