name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:
    paths-ignore:
      - docs/**
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  flutter-channel: stable

jobs:
  formatting-dart:
    name: Formatting - Dart
    timeout-minutes: 10
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          channel: ${{ env.flutter-channel }}
          cache: true
          pub-cache-hash-pattern: pubspec.lock

      - name: Setup Melos
        run: dart pub global activate melos

      - name: Install daco
        run: dart pub global activate daco

      - name: Get dependencies
        run: dart pub get

      - name: Check formatting
        run: melos formatting:check

      - name: Print diff
        if: failure()
        run: git diff

  formatting-clang:
    name: Formatting - Clang
    timeout-minutes: 10
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: '21'
          check-path: 'packages/cbl/native/couchbase-lite-dart'

  analyze-dart:
    name: Analyze Dart code
    timeout-minutes: 10
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          channel: ${{ env.flutter-channel }}
          cache: true
          pub-cache-hash-pattern: pubspec.lock

      - name: Setup Melos
        run: dart pub global activate melos

      - name: Bootstrap repository
        shell: bash
        run: melos bootstrap

      - name: Analyze Dart code
        run: melos analyze

  test-dart-unit:
    name: Dart unit tests
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        package: [cbl, cbl_sentry, cbl_generator]
        embedder: [standalone]
        os: [Ubuntu]
        include:
          - package: cbl
            embedder: standalone
            os: macOS
          - package: cbl
            embedder: standalone
            os: Windows
    env:
      EMBEDDER: ${{ matrix.embedder }}
      TARGET_OS: ${{ matrix.os }}
      TEST_PACKAGE: ${{ matrix.package }}
    runs-on: >-
      ${{ fromJSON('{
        "Ubuntu":"blacksmith-2vcpu-ubuntu-2204",
        "macOS":"macos-15",
        "Windows":"windows-2025"
      }')[matrix.os] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell

      - name: Install Linux cross-compilation toolchain
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          channel: ${{ env.flutter-channel }}
          cache: true
          pub-cache-hash-pattern: pubspec.lock

      - name: Get dependencies
        run: dart pub get

      - name: Bootstrap repository
        shell: bash
        run: dart run melos bootstrap

      - name: Run build_runner
        if: ${{ matrix.package == 'cbl_generator' }}
        shell: bash
        run: ./tools/ci-steps.sh checkBuildRunnerOutput

      - name: Run tests
        shell: bash
        run: ./tools/ci-steps.sh runUnitTests

      - name: Upload coverage data
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        shell: bash
        run: |
          ./tools/ci-steps.sh uploadCoverageData "unit.${{ matrix.package }}"

  test-e2e:
    name: E2E tests
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        embedder: [standalone, flutter]
        os:
          - iOS
          - macOS
          - Android
          - Ubuntu
          - Windows
        exclude:
          - embedder: standalone
            os: iOS
          - embedder: standalone
            os: Android
    runs-on: >-
      ${{ matrix.os == 'macOS' && matrix.embedder == 'standalone' && 'macos-15'
       || fromJSON('{
        "iOS":"warp-macos-15-arm64-6x",
        "macOS":"warp-macos-15-arm64-6x",
        "Android":"blacksmith-4vcpu-ubuntu-2204",
        "Ubuntu":"blacksmith-2vcpu-ubuntu-2204",
        "Windows":"windows-2025"
      }')[matrix.os] }}
    env:
      EMBEDDER: ${{ matrix.embedder }}
      TARGET_OS: ${{ matrix.os }}
      TEST_PACKAGE: >-
        ${{ fromJSON('{
          "standalone":"cbl_e2e_tests_standalone_dart",
          "flutter":"cbl_e2e_tests_flutter"
        }')[matrix.embedder] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell

      - name: Select Java 17
        if: ${{ matrix.os == 'Android' }}
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Cache Android NDK and CMake
        if: ${{ matrix.os == 'Android' }}
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk/ndk/28.0.13004108
            /usr/local/lib/android/sdk/ndk/28.2.13676358
            /usr/local/lib/android/sdk/cmake/3.18.1
            /usr/local/lib/android/sdk/platforms/android-33
            /usr/local/lib/android/sdk/platforms/android-36
          key: android-ndk-28.0.13004108-28.2.13676358-cmake-3.18.1-platforms-33-36

      - name: Install Android Native Toolchain
        if: ${{ matrix.os == 'Android' }}
        run: ./tools/android-sdk.sh installNativeToolchain

      - name: Install Android App Build Dependencies
        if: ${{ matrix.os == 'Android' }}
        run: ./tools/android-sdk.sh installAppBuildDeps

      - name: Setup Gradle
        if: ${{ matrix.os == 'Android' }}
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Cache apt packages
        if: matrix.os == 'Ubuntu' && matrix.embedder == 'flutter'
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: apt-flutter-linux-desktop-${{ runner.os }}

      - name: Install Flutter Linux Desktop dependencies
        if: matrix.os == 'Ubuntu' && matrix.embedder == 'flutter'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends clang cmake ninja-build pkg-config libgtk-3-dev lld

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
        with:
          channel: ${{ env.flutter-channel }}
          cache: true
          pub-cache-hash-pattern: pubspec.lock
          cache-provider: ${{ ((matrix.os == 'macOS' || matrix.os == 'iOS') && matrix.embedder == 'flutter') && 'warp' || 'github' }}

      - name: Enable Flutter native assets
        if: matrix.embedder == 'flutter'
        run: flutter config --enable-native-assets

      - name: Get dependencies
        run: dart pub get

      - name: Bootstrap repository
        shell: bash
        run: dart run melos bootstrap

      - name: Start Couchbase services
        shell: bash
        run: ./tools/ci-steps.sh startCouchbaseServices

      - name: Cache Android emulator
        if: matrix.os == 'Android'
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk/system-images/android-27
          key: android-system-image-27-x86_64-v2

      - name: Start virtual devices
        if: matrix.embedder == 'flutter'
        shell: bash
        run: ./tools/ci-steps.sh startVirtualDevices

      - name: Run tests
        shell: bash
        run: ./tools/ci-steps.sh runE2ETests

      - name: Collect test results
        if: failure()
        shell: bash
        run: ./tools/ci-steps.sh collectTestResults

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.embedder }}
          path: test-results

      - name: Upload coverage data
        # Disabled until we figure out how to get coverage data from flutter tests
        if: ${{ matrix.embedder != 'flutter' }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        shell: bash
        run: |
          ./tools/ci-steps.sh uploadCoverageData "e2e.cbl.${{ matrix.embedder }}.${{ matrix.os }}"

